import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {approveChecks,requireChecks,verifyAcceptance} from '../src/acceptance/checks.ts';
import {captureBaseline} from '../src/workspace/candidate.ts';import {loadConfig} from '../src/config.ts';
import {SERVER_MODULE,SERVER_DIGEST} from '../src/acceptance/server-runtime.ts';import {ASSET_MODULE,ASSET_DIGEST} from '../src/acceptance/asset-runtime.ts';
const configured=!!process.env.HARNESS_DOCKER&&!!process.env.HARNESS_IMAGE_ID;
test('Docker: pinned parsers run offline, detect missing assets and disguised SQLite leaks, and remain read-only',{skip:configured?false:'configure Docker for parser verification'},async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'assets-docker-')),project=path.join(root,'project');await mkdir(project);
 const app=String.raw`import http from 'node:http';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
const mode=process.env.MODE;const db=new DatabaseSync(process.env.APP_DB);db.exec('PRAGMA journal_mode=WAL; CREATE TABLE sample(value TEXT); INSERT INTO sample VALUES (\'fiction\')');
const routes={'/':['text/html','<base href="/files/"><script type=module src=a.js></script><link rel=stylesheet href=a.css><img src=image.png><template><template></template><img src=missing></template>'],'/files/a.js':['text/javascript',"// import './missing.js'\nimport './b.js';"],'/files/b.js':['text/javascript','export const n=1;'],'/files/a.css':['text/css','/* url(missing.png) */ body {background:url(image.png)}'],'/files/image.png':['image/png',Buffer.from([10,20,30])]};
http.createServer((q,r)=>{let item=routes[q.url];if(mode==='missing'&&q.url==='/files/b.js')item=undefined;if(q.headers.origin!==('http://'+q.headers.host)){r.writeHead(403);r.end();return;}if(!item){r.writeHead(404);r.end('missing');return;}
let body=item[1];if(q.url==='/files/image.png'&&mode.startsWith('leak'))body=Buffer.concat([Buffer.from('prefix'),fs.readFileSync(process.env.APP_DB+(mode==='leak-sidecar'?'-shm':'')),Buffer.from('suffix')]);r.writeHead(200,{'content-type':item[0]});r.end(body);}).listen(0,'127.0.0.1',function(){console.log('Listening at http://127.0.0.1:'+this.address().port)});`;
 const probe=String.raw`import assert from 'node:assert/strict';import {readFile,readdir,writeFile,realpath} from 'node:fs/promises';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {withServer} from '${SERVER_MODULE}';import {collectAssets,assertNoDatabaseBytes} from '${ASSET_MODULE}';
await assert.rejects(writeFile('/harness-checks/node_modules/parse5/package.json','tampered'));await withServer({command:['node','app.js'],databaseEnv:'APP_DB',env:{MODE:await readFile('/work/mode','utf8')},ready:/^Listening at (http:\/\/127\.0\.0\.1:\d+)$/},async app=>{
const names=()=>readdir(app.directory);const snapshots=async()=>Promise.all((await names()).filter(n=>n===path.basename(app.database)||n.startsWith(path.basename(app.database)+'-')).map(async n=>{const file=await realpath(path.join(app.directory,n));assert.ok(file!='/work'&&!file.startsWith('/work/'));return readFile(file)}));const before=await snapshots();const db=new DatabaseSync(app.database,{readOnly:true});assert.equal(db.prepare('SELECT value FROM sample').get().value,'fiction');db.close();
const evidence=await collectAssets(app.url,{headers:{Origin:new URL(app.url).origin}});assert.deepEqual(evidence.unresolved,[]);assert.deepEqual(evidence.external,[]);assertNoDatabaseBytes(evidence.responses,[...before,...await snapshots()]);console.log(evidence.responses[0].status+':'+evidence.responses.length);});`;
 try{
  await writeFile(path.join(project,'package.json'),'{"type":"module"}');await writeFile(path.join(project,'app.js'),app);await writeFile(path.join(project,'mode'),'good');
  const file=path.join(root,'checks.json');await writeFile(file,JSON.stringify({version:1,cases:[{id:'assets',tasks:['web'],steps:[{command:['node','--input-type=module','-e',probe],assetRuntime:ASSET_DIGEST,serverRuntime:SERVER_DIGEST,exitCode:0,stdout:'200:5\n'}]},{id:'server-only',tasks:['web'],steps:[{command:['node','--input-type=module','-e',"import {readdir} from 'node:fs/promises';console.log((await readdir('/harness-checks')).join(','))"],serverRuntime:SERVER_DIGEST,exitCode:0,stdout:'server.mjs\n'}]}]}));await approveChecks(project,file);const approved=await requireChecks(project,['web']);const config=loadConfig();
  for(const mode of ['good','missing','leak-db','leak-sidecar']){await writeFile(path.join(project,'mode'),mode);const candidate=await captureBaseline(project,path.join(root,mode));const result=verifyAcceptance(project,candidate,['web'],config,approved);if(mode==='good')assert.equal((await result).summaries.length,2);else await assert.rejects(result,/expected exit 0/);}
 }finally{await rm(root,{recursive:true,force:true});}
});
