import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {parseMetalSpec,validateCheckpoint,context,trainingInput} from '../src/metal/schema.ts';
import {approveMetal,readMetal,readMetalState,saveMetalState} from '../src/metal/store.ts';
import {trainMetal,evaluateMetal,recoverMetal,type Engine} from '../src/metal/workflow.ts';
import {fingerprint} from '../src/ml/schema.ts';import {metalProtocol,type MetalRuntime} from '../src/metal/runtime.ts';
const runtime={profile:{},protocol:await metalProtocol(),host:'test'} as MetalRuntime;
const spec={version:1,title:'Prediction',target:'y',seed:42,epochs:20,learningRate:0.05,maxRmse:100,minImprovement:0,checkpointEvery:10,limits:{timeoutSeconds:60,totalSeconds:240,maxAttempts:4}};
const csv='id,x,y\n'+Array.from({length:40},(_,i)=>`r${i},${i},${3+2*i}`).join('\n');
async function fixture(t:any){const root=await mkdtemp(path.join(os.tmpdir(),'metal-test-'));t.after(()=>rm(root,{recursive:true,force:true}));const project=root+'/project';await (await import('node:fs/promises')).mkdir(project);await writeFile(root+'/data.csv',csv);const a=await approveMetal(project,root+'/data.csv',spec,runtime);return {project,a};}
function checkpoint(a:any,from:number,to:number){return {version:1,binding:a.digest,from,device:'Test GPU',dispatches:2*(to-from),model:{...context(a),version:1,kind:'linear-regression@1',completed:to,weights:[1],bias:2}};}
const engine:Engine={runtime:async()=>runtime,run:async(_p,a,_t,prior,to)=>checkpoint(a,prior?.model.completed??0,to),recover:async()=>null};
test('Metal spec bounds segment and total budgets without ignoring unknown fields',()=>{assert.equal(parseMetalSpec(spec).checkpointEvery,10);for(const bad of [{...spec,checkpointEvery:0},{...spec,checkpointEvery:21},{...spec,limits:{...spec.limits,maxAttempts:1}},{...spec,gpu:'cpu'},{...spec,limits:{...spec.limits,timeoutSeconds:601}}])assert.throws(()=>parseMetalSpec(bad));});
test('Checkpoints bind data, recipe, parameters, device and exact progress; inputs exclude holdout',async t=>{const {project,a}=await fixture(t),data=await readMetal(project,a.id),c=checkpoint(a,0,10);assert.equal(validateCheckpoint(c,a,0,10).model.completed,10);for(const bad of [{...c,binding:'0'.repeat(64)},{...c,dispatches:0},{...c,device:''},{...c,model:{...c.model,completed:11}},{...c,model:{...c.model,weights:[NaN]}}])assert.throws(()=>validateCheckpoint(bad,a,0,10));assert.throws(()=>validateCheckpoint({...c,from:10,model:{...c.model,completed:20}},a,10,20,'Other GPU'));const input=trainingInput(a,data.train,null,10);for(const row of data.holdout)assert.ok(!input.rows.some(r=>r.id===row.id));assert.ok(!('holdout' in input));});
test('Interrupted segment preserves checkpoint, budgets stay spent and resume starts at saved progress',async t=>{const {project,a}=await fixture(t);let n=0;const interrupted={...engine,run:async(...args:Parameters<Engine['run']>)=>{if(++n===2)throw Error('interrupted');return engine.run(...args);}};await assert.rejects(trainMetal(project,a.id,()=>{},false,interrupted),/interrupted/);const s=await readMetalState(project,a.id);assert.equal(s.checkpoint?.model.completed,10);assert.equal(s.attempts.length,2);assert.equal(s.status,'paused');await trainMetal(project,a.id,()=>{},false,engine);const done=await readMetalState(project,a.id);assert.equal(done.checkpoint?.model.completed,20);assert.equal(done.attempts.length,3);const report=await evaluateMetal(project,a.id);assert.equal(typeof report.passed,'boolean');assert.equal((await readMetalState(project,a.id)).evaluatedHash,fingerprint(done.checkpoint!.model));});
test('Budget exhaustion and runtime drift refuse new work; completed evaluation prevents retraining',async t=>{const {project,a}=await fixture(t);await assert.rejects(trainMetal(project,a.id,()=>{},false,{...engine,runtime:async()=>({...runtime,host:'changed'})}),/runtime changed/);let s=await readMetalState(project,a.id);assert.equal(s.attempts.length,0);const broken={...engine,run:async()=>{throw Error('stopped');}};for(let i=0;i<4;i++)await assert.rejects(trainMetal(project,a.id,()=>{},false,broken));await assert.rejects(trainMetal(project,a.id,()=>{},false,engine),/budget/);});
test('Dead-controller recovery promotes only a valid completed native result',async t=>{const {project,a}=await fixture(t);let s=await readMetalState(project,a.id);s.attempts.push({index:1,from:0,to:10,status:'running'});s.status='running';s.controllerPid=2147483647;await saveMetalState(project,s);await recoverMetal(project,a.id,{...engine,recover:async()=>checkpoint(a,0,10)});s=await readMetalState(project,a.id);assert.equal(s.checkpoint?.model.completed,10);assert.equal(s.status,'paused');s.attempts.push({index:2,from:10,to:20,status:'running'});s.status='running';await saveMetalState(project,s);await assert.rejects(recoverMetal(project,a.id,{...engine,recover:async()=>checkpoint({...a,digest:'wrong'},10,20)}),/checkpoint/i);assert.equal((await readMetalState(project,a.id)).checkpoint?.model.completed,10);});

test('Native shutdown retries only the unconfirmed-stop race and stays bounded',async()=>{const {recoverOwnedNative}=await import('../src/metal/engine.ts');let calls=0;await recoverOwnedNative('p','id',async()=>{if(++calls<3)throw Error('Cannot confirm VM stopped; files retained.');},async()=>{});assert.equal(calls,3);calls=0;await assert.rejects(recoverOwnedNative('p','id',async()=>{calls++;throw Error('foreign owner');},async()=>{}),/foreign/);assert.equal(calls,1);calls=0;await assert.rejects(recoverOwnedNative('p','id',async()=>{calls++;throw Error('Cannot confirm VM stopped; files retained.');},async()=>{}));assert.equal(calls,5);});
test('Changed data is refused and failed quality cannot be exported or retrained',async t=>{const {project,a}=await fixture(t);await trainMetal(project,a.id,()=>{},false,engine);const report=await evaluateMetal(project,a.id);assert.equal(report.passed,false);await assert.rejects(trainMetal(project,a.id,()=>{},false,engine),/already been evaluated/);const {exportMetal}=await import('../src/metal/workflow.ts');await assert.rejects(exportMetal(project,a.id,project+'/model.json'),/passed holdout/);const {metalDirectory}=await import('../src/metal/store.ts');await writeFile((await metalDirectory(project,a.id))+'/train.json','[]');await assert.rejects(readMetal(project,a.id),/dataset/);});
test('Guided Metal setup requires approval and shows checkpoint, quality and resource scope',async t=>{const {project}=await fixture(t);const {metalSetup,guideMetal}=await import('../src/guide/metal.ts');const {listMetal}=await import('../src/metal/store.ts');const lines:string[]=[];const answers=[path.dirname(project)+'/data.csv','y','Guided regression','20','10','1','10','4','n'];const io={write:(s:string)=>{lines.push(s);},ask:async(q:string)=>{lines.push(q);assert.ok(answers.length,q);return answers.shift()!;}};await metalSetup(project,io,async()=>runtime);assert.equal((await listMetal(project)).length,1);assert.match(lines.join('\n'),/80\/20/);assert.match(lines.join('\n'),/300s/);assert.match(lines.join('\n'),/Holdout evaluation is separate/);const choices=['5','0'],commands:string[][]=[];await guideMetal(project,{write:()=>{},ask:async()=>choices.shift()??'0'},async(_p,args)=>{commands.push([...args]);return 0;});assert.deepEqual(commands[0]?.slice(0,2),['metal','train']);});
test('Retirement prevents resume and corrupted checkpoint bytes are rejected',async t=>{const {project,a}=await fixture(t);await trainMetal(project,a.id,()=>{},true,engine);const {releaseMetal}=await import('../src/metal/workflow.ts');const s=await readMetalState(project,a.id);s.checkpoint!.model.weights[0]=999;await saveMetalState(project,s);await assert.rejects(readMetalState(project,a.id),/corrupt/);s.checkpoint!.model.weights[0]=1;await saveMetalState(project,s);await releaseMetal(project,a.id);await assert.rejects(trainMetal(project,a.id,()=>{},false,engine),/retired/);});
test('Passing quality exports inert JSON outside project; active model references cannot be released',async t=>{const {project,a}=await fixture(t);const perfect:Engine={...engine,run:async(_p,a,_rows,prior,to)=>{const c=checkpoint(a,prior?.model.completed??0,to);c.model.weights=[2*a.preprocessing.scales[0]!];c.model.bias=3+2*a.preprocessing.means[0]!;return c;}};await trainMetal(project,a.id,()=>{},false,perfect);assert.equal((await evaluateMetal(project,a.id)).passed,true);const {exportMetal}=await import('../src/metal/workflow.ts');const {readFile}=await import('node:fs/promises');const destination=path.dirname(project)+'/model.json';await exportMetal(project,a.id,destination);assert.equal(JSON.parse(await readFile(destination,'utf8')).kind,'linear-regression@1');await assert.rejects(exportMetal(project,a.id,destination),{code:'EEXIST'});await assert.rejects(exportMetal(project,a.id,project+'/model.json'),/outside project/);const {artifactsCommand}=await import('../src/verbs/artifacts.ts');await assert.rejects(artifactsCommand(project,['release',a.id,'--yes']),/Cannot release/);});
