import {productEvidence} from '../src/view/product.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,realpath,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';
import {draftProduct,approveProduct} from '../src/product/spec.ts';import {productReport} from '../src/product/report.ts';import {approvePerformance,inspectEnvironment,parseRun} from '../src/performance/store.ts';import {verifyPerformance,recoverPerformance,appArguments,probeArguments} from '../src/performance/controller.ts';import {performanceReport,recordPerformanceAssessment} from '../src/performance/report.ts';import {recoverWriter} from '../src/workspace/writer-lock.ts';import {artifactBytes} from '../src/artifacts/store.ts';import {profile} from './performance-fixture.ts';import {run} from '../src/run.ts';
test('benchmark containers isolate app from sampler and fixed instrumentation parses',async()=>{
 const r:any={id:'performance-run-fixture',token:'fixture',image:'sha256:'+'a'.repeat(64),containers:['app','probe']},a=appArguments(r,'app','/owned/source',profile),p=probeArguments(r,'probe','app','/owned',profile);
 assert.ok(a.includes('--pull=never'));assert.ok(a.includes('--network=none'));assert.ok(a.includes('--cpus=2'));assert.ok(p.includes('--cpus=1'));assert.ok(a.includes('--security-opt=no-new-privileges'));assert.ok(p.includes('container:app'));assert.ok(!a.join(' ').includes('/harness-checks'));assert.ok(!p.join(' ').includes('/owned/source'));
 for(const file of ['probe.mjs','json.mjs']){const r=await run(process.execPath,['--check',new URL('../src/performance/instrumentation/'+file,import.meta.url).pathname]);assert.equal(r.code,0,r.stderr);}
});
test('real bounded benchmarks: repeated positive, slow/wrong replies, timeouts, partial cancellation and controller loss',{skip:!process.env.HARNESS_VERIFY_PERFORMANCE,timeout:180000},async()=>{
 const root=await realpath(await mkdtemp(path.join(os.tmpdir(),'performance-live-'))),docker=process.env.HARNESS_DOCKER??'/usr/local/bin/docker',image=process.env.HARNESS_IMAGE_ID!,environment=await inspectEnvironment(docker,image);let success=false;
 try{for(const fault of ['none','repeat','slow','wrong','timeout','cancel','crash','runtime']){
  const project=root+'/'+fault;await mkdir(project+'/src',{recursive:true});await writeFile(project+'/package.json','{"name":"performance-fixture","type":"module"}');await writeFile(project+'/features.json',JSON.stringify([{id:'api',title:'Local API',priority:'must',status:'done',criteria:['Correct response'],dependsOn:[]} ]));
  await writeFile(project+'/src/server.js',`import http from 'node:http';const fault=${JSON.stringify(fault)};let requests=0;http.createServer((req,res)=>{requests++;const delay=fault==='slow'?100:fault==='cancel'||fault==='crash'?30:fault==='timeout'&&requests>3?1000:10;setTimeout(()=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({status:fault==='wrong'?'wrong':'ok'}));},delay);}).listen(Number(process.env.PORT),'127.0.0.1');`);
  const product=await draftProduct(project,'api','prototype',[]);await approveProduct(project,product);await approvePerformance(project,{...profile,meanMs:60,maxSpreadPercent:100,samples:['cancel','crash'].includes(fault)?50:5},fault==='runtime'?{...environment,kernel:'changed-approved-runtime'}:environment);const source=(await productReport(project)).source!;let r;
  if(fault==='crash'){
   const code=`import {verifyPerformance} from ${JSON.stringify(new URL('../src/performance/controller.ts',import.meta.url).href)};await verifyPerformance(${JSON.stringify(project)},()=>{},${JSON.stringify(docker)});`;
   const child=spawn(process.execPath,['--input-type=module','-e',code],{stdio:'ignore'});const exited=once(child,'exit');let id;
   try{const deadline=Date.now()+15000;while(Date.now()<deadline){const ids=await readdir(project+'-harness/performance/runs');id=ids[0];if(id){try{const o=JSON.parse(await readFile(project+'-harness/performance/runs/'+id+'/output/samples.json','utf8'));if(o.rounds[0]?.samples.length)break;}catch{}}await new Promise(r=>setTimeout(r,40));}assert.ok(id);child.kill('SIGKILL');await exited;const owner=JSON.parse(await readFile(project+'-harness.writer-lock','utf8'));await recoverWriter(project,owner.token);await recoverPerformance(project,id!);r=parseRun(JSON.parse(await readFile(project+'-harness/performance/runs/'+id+'/state.json','utf8')));}finally{child.kill('SIGKILL');}
  }else{let timer:ReturnType<typeof setTimeout>|undefined;try{r=await verifyPerformance(project,message=>{console.log(fault+': '+message);if(fault==='cancel'&&message.startsWith('Running approved'))timer=setTimeout(()=>process.emit('SIGTERM'),900);},docker);}finally{if(timer)clearTimeout(timer);}}
  assert.deepEqual(r.containers,[]);const ps=await run(docker,['ps','-aq','--filter',`label=harness.performance=${r.id}`]);assert.equal(ps.stdout.trim(),'');
  const report=await performanceReport(project,{source,product:product.digest});
  if(['none','repeat'].includes(fault)){assert.equal(r.status,'passed',r.message);assert.equal(report.metrics?.samples,15);assert.equal(report.metrics?.errors,0);assert.ok(report.metrics!.spreadPercent<=100);await recordPerformanceAssessment(project,report,true,'Reviewed the fixture workload and repeated warm laptop/container measurements.');assert.equal((await performanceReport(project,{source,product:product.digest})).status,'passed');}
  else if(['cancel','crash'].includes(fault)){assert.equal(r.status,'interrupted');assert.ok(r.report,'partial artifact retained');const o=JSON.parse((await artifactBytes(project,r.report!)).toString());assert.equal(o.complete,false);assert.ok(o.rounds.length);assert.equal(report.complete,false);}
  else if(fault==='runtime'){assert.equal(r.status,'failed');assert.ok(r.message.includes('runtime validation'));assert.equal(report.complete,false);assert.equal(r.report,undefined);}
  else{assert.equal(r.status,'failed',r.message);assert.equal(report.complete,false);assert.ok(report.failures.includes(fault==='slow'?'mean latency':fault==='wrong'?'response correctness':'error rate'),JSON.stringify(report));}
  const panel=productEvidence(await productReport(project),undefined);assert.match(panel,/Measurement limitations/);if(['none','repeat'].includes(fault))assert.match(panel,/Local API measurements/);
 }success=true;}finally{if(success)await rm(root,{recursive:true,force:true});else console.log('Retained benchmark fixture: '+root);}
});
