import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,realpath,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {init} from '../src/verbs/init.ts';import {approveTorch,readTorch} from '../src/torch/store.ts';import {approveMetal,readMetal} from '../src/metal/store.ts';import {context,trainingInput} from '../src/metal/schema.ts';import {metalProtocol,resources} from '../src/metal/runtime.ts';import {protocolHash} from '../src/native/provision.ts';
import {createJob,saveJob} from '../src/jobs/state.ts';import {TORCH_COMMAND} from '../src/torch/recipe.ts';import {assessTorch,predictTorch} from '../src/torch/schema.ts';import {fingerprint,hash,predict,assessPredictions} from '../src/ml/schema.ts';import {saveJson,putArtifact} from '../src/artifacts/store.ts';
import {approveNative} from '../src/native/store.ts';import {mlChoices} from '../src/product/evidence/ml.ts';import {collectEvidence} from '../src/product/evidence/desktop.ts';
const h='b'.repeat(64),source='a'.repeat(64),image='sha256:'+h;
async function fixture(kind:'torch'|'metal',fn:(f:any)=>Promise<void>){const root=await realpath(await mkdtemp(path.join(os.tmpdir(),'product-ml-models-'))),project=root+'/app';await mkdir(project);try{
 await init(project,['--python']);const spec={version:1,title:'Synthetic '+kind,seed:42,limits:{timeoutSeconds:120,totalSeconds:240,maxAttempts:2}};
 let a:any,state:any,report:any,artifact:any,cp:any,job:any,dir:string,namespace:string|undefined;
 if(kind==='torch'){
 const file=root+'/data.json';await writeFile(file,JSON.stringify({features:['x'],rows:Array.from({length:30},(_,i)=>({id:'r'+i,x:[i<15?-2-i/30:2+i/30]}))}));a=await approveTorch(project,file,{...spec,kind:'kmeans',steps:5,learningRate:0.01,batchSize:8,clusters:2,maxError:1},image);const {train,holdout}=await readTorch(project,a.id);
 job=await createJob(project,{version:1,title:spec.title,command:TORCH_COMMAND,outputs:['model.json'],checkpoint:{protocol:'json-step@1',total:5},limits:spec.limits,recipe:{id:'torch-cpu',version:1,approvalId:a.id,approvalDigest:a.digest}});
 Object.assign(job,{status:'succeeded',attempts:1,reservedSeconds:120,source:{directory:'fixture',digest:source,files:{}},image,profile:{},capabilities:{},environment:h,installPolicy:{}});job.identity=fingerprint({version:1,protocol:'json-step@1',spec:job.specDigest,source,profile:job.profile,capabilities:job.capabilities,environment:job.environment,policy:job.installPolicy});
 const model={version:1,kind:'kmeans',context:a.digest,completed:5,weights:null,centers:[[-1],[1]]};const payload={protocol:'torch-cpu@1',context:a.digest,completed:5,runtime:'2.14.0+cpu',model:null,optimizer:null,scheduler:null,torchRng:Array(5056).fill(0),pythonRng:[3,{tuple:Array(625).fill(0)},null],permutation:[],cursor:0,epoch:0,losses:Array(5).fill(1),centers:model.centers};
 cp=await putArtifact(project,'checkpoint.json',Buffer.from(JSON.stringify({version:1,protocol:'json-step@1',identity:job.identity,completed:5,total:5,payload})),{producer:job.id,input:source,environment:job.identity,verification:'unverified'});const trained=await putArtifact(project,'model.json',Buffer.from(JSON.stringify(model)),{producer:job.id,input:source,environment:job.identity,verification:'unverified'});job.completed=5;job.checkpoint=cp.id;job.artifacts=[trained.id];await saveJob(project,job,'succeeded','Synthetic');
 const values=predictTorch(model,holdout,a.means,a.scales),score=assessTorch('kmeans',values,holdout.map(()=>0),1),baseline=holdout.reduce((s,r)=>s+r.x.reduce((v,x,i)=>v+((x-a.means[i])/a.scales[i])**2,0),0)/holdout.length;
 report={...score,baseline,passed:score.passed&&score.error<baseline,rows:holdout.length,candidateHash:trained.sha256,limitation:'Distance measures compactness, not useful semantic groups.'};assert.equal(report.passed,true);
 artifact=await putArtifact(project,'torch-model.json',Buffer.from(JSON.stringify({...model,features:a.features,means:a.means,scales:a.scales})),{producer:a.id,input:a.digest,environment:job.identity,verification:'evaluation-passed',evaluation:{approval:a.digest,reportHash:fingerprint(report)}});state={id:a.id,status:'passed',jobId:job.id,candidateHash:trained.sha256,report,artifact:artifact.id};dir=project+'-harness/torch/'+a.id;
 }else{
 const profile={version:1 as const,tart:'/fixture/tart',tartHash:h,networkHash:h,cloneHash:h,image:'harness-macos-fixture',files:{'disk.img':h,'nvram.bin':h,'config.json':h},identities:{'disk.img':h,'nvram.bin':h,'config.json':h},protocol:await protocolHash(),cpu:2 as const,memoryMiB:4096 as const,os:'26.6.2',arch:'arm64' as const};
 const file=root+'/data.csv';await writeFile(file,'id,x,y\n'+Array.from({length:30},(_,i)=>`r${i},${i},${2*i+3}`).join('\n'));a=await approveMetal(project,file,{...spec,target:'y',epochs:10,learningRate:0.05,maxRmse:0.01,minImprovement:0.9,checkpointEvery:10},{profile,protocol:await metalProtocol(),host:'darwin/arm64/25.6.0'});const {train,holdout}=await readMetal(project,a.id);
 const model={...context(a),version:1,kind:'linear-regression@1',completed:10,weights:[2*a.preprocessing.scales[0]],bias:3+2*a.preprocessing.means[0]};const point={version:1,binding:a.digest,from:0,device:'Synthetic GPU',dispatches:20,model};dir=project+'-harness/metal/'+a.id;const candidate=dir+'/segment-1';await mkdir(candidate);const na=await approveNative(candidate,{version:1,title:a.spec.title,entry:'run.sh',timeoutSeconds:120,expectedExit:0,stdout:'Metal checkpoint ready\n',artifacts:['checkpoint.json']},profile);
 const files:Record<string,string>={'input.json':hash(JSON.stringify(trainingInput(a,train,null,10))),'package.json':hash('{"name":"harness-metal-training","private":true}')};for(const name of ['train.swift','run.sh'])files[name]=hash(await readFile(path.join(resources,name)));const input=fingerprint(Object.entries(files).sort(([a],[b])=>a.localeCompare(b))),nid='native-11111111-1111-4111-8111-111111111111',artifacts=[];
 for(const [name,bytes]of [['checkpoint.json',JSON.stringify(point)],['stdout.txt','Metal checkpoint ready\n'],['assessment.json',JSON.stringify({passed:true,expectedExit:0,observedExit:0,stdoutMatches:true})]]){const f=await putArtifact(candidate,name!,Buffer.from(bytes!),{producer:nid,input,environment:fingerprint(profile),verification:'unverified'});artifacts.push(f.id);if(name==='checkpoint.json')cp=f;}
 const nr=candidate+'-harness/native/runs/'+nid;await mkdir(nr,{recursive:true});job={version:1,id:nid,token:'fixture',approval:na.id,profileDigest:fingerprint(profile),status:'passed',message:'Synthetic',at:new Date().toISOString(),artifacts,source:input,outputMounted:false,vmStarted:true,controllerPid:1};await saveJson(nr,'state.json',job);namespace=candidate+'-harness';
 report=assessPredictions(holdout.map(r=>predict(model as any,r.x)),holdout.map(r=>r.y),a.baseline,a.spec);artifact=await putArtifact(project,'metal-model.json',Buffer.from(JSON.stringify(model)),{producer:a.id,input:a.digest,environment:fingerprint(a.runtime),verification:'evaluation-passed',evaluation:{approval:a.digest,reportHash:fingerprint(report)}});state={version:1,id:a.id,status:'passed',attempts:[{index:1,from:0,to:10,status:'completed'}],checkpoint:point,checkpointHash:fingerprint(point),evaluatedHash:fingerprint(model),assessment:report,artifact:artifact.id};
 }
 await saveJson(dir,'state.json',state);const scope={version:1 as const,targets:[(await mlChoices(project))[0]!.target]};await fn({project,dir,a,state,scope,artifact,cp,job,namespace});
 }finally{await rm(root,{recursive:true,force:true});}}
for(const kind of ['torch','metal'] as const){
 test(kind+' fixture independently scores retained model and keeps unproven recovery missing',async()=>fixture(kind,async f=>{const r=await collectEvidence(f.project,source,f.scope);assert.equal(r.records[0]!.outcome,'passed',r.records[0]!.detail);assert.equal(r.records[1]!.outcome,'passed');assert.equal(r.records[2]!.applicability,'missing');assert.ok(r.records[0]!.metrics![0]!.samples>0);if(kind==='torch')assert.match(r.records[0]!.limitations.join(' '),/compactness/);}));
 for(const fault of ['score','model','checkpoint','runtime'])test(kind+' fixture rejects '+fault,async()=>fixture(kind,async f=>{
  if(fault==='score'){if(kind==='torch')f.state.report.error=999;else f.state.assessment.rmse=999;await saveJson(f.dir,'state.json',f.state);}
  if(fault==='model')await writeFile(f.project+'-harness/artifacts/blobs/'+f.artifact.sha256,'{}');
  if(fault==='checkpoint')await rm((f.namespace??f.project+'-harness')+'/artifacts/manifests/'+f.cp.id+'.json');
  if(fault==='runtime')f.scope.targets[0].runtime='0'.repeat(64);
  assert.notEqual((await collectEvidence(f.project,source,f.scope)).records[0]!.outcome,'passed');
 }));
}
test('Metal wrapper cannot conceal a running or mounted native segment',async()=>fixture('metal',async f=>{f.job.outputMounted=true;await saveJson(f.namespace+'/native/runs/'+f.job.id,'state.json',f.job);assert.notEqual((await collectEvidence(f.project,source,f.scope)).records[0]!.outcome,'passed');}));
import {completeTorchCheckpoint} from '../src/product/evidence/torch-checkpoint.ts';
function classifierCheckpoint(){const shapes:Record<string,number[]>={'0.weight':[16,1],'0.bias':[16],'3.weight':[8,16],'3.bias':[8],'5.weight':[2,8],'5.bias':[2]};const dict=(v:Record<string,unknown>)=>({dict:Object.entries(v)}),tensor=(shape:number[]):any=>({tensor:shape.length?Array.from({length:shape[0]!},()=>tensor(shape.slice(1)).tensor):0,dtype:'float32'});
 const a:any={digest:h,features:['x'],spec:{kind:'classifier',learningRate:0.01,clusters:2}};
 const p:any={protocol:'torch-cpu@1',context:h,completed:5,runtime:'2.14.0+cpu',model:dict(Object.fromEntries(Object.entries(shapes).map(([k,s])=>[k,tensor(s)]))),optimizer:dict({state:{dict:Object.values(shapes).map((s,i)=>[i,dict({step:{tensor:5,dtype:'float32'},exp_avg:tensor(s),exp_avg_sq:tensor(s)})])},param_groups:[dict({params:[0,1,2,3,4,5],lr:0.01})]}),scheduler:dict({last_epoch:5,_step_count:6,step_size:20,gamma:0.9,base_lrs:[0.01],_last_lr:[0.01]}),torchRng:Array(5056).fill(0),pythonRng:[3,{tuple:Array(625).fill(0)},null],permutation:Array.from({length:24},(_,i)=>i),cursor:8,epoch:2,losses:Array(5).fill(1),centers:null};return {p,a};}
test('classifier checkpoint completeness checks packed Adam tensors, scheduler, RNG and sampler without executing them',()=>{
 const {p,a}=classifierCheckpoint();assert.doesNotThrow(()=>completeTorchCheckpoint(p,a,5,24));
 for(const change of [(p:any)=>{p.optimizer.dict[0][1].dict[0][1].dict.pop();},(p:any)=>{p.scheduler.dict[0][1]=3;},(p:any)=>{p.pythonRng[1].tuple[0]=-1;},(p:any)=>{p.permutation.pop();},(p:any)=>{p.model.dict[0][1].tensor=[];}]){const broken=structuredClone(p);change(broken);assert.throws(()=>completeTorchCheckpoint(broken,a,5,24));}
});
