import type {ProductReport} from '../src/product/report.ts';
import {observation,profile,environment} from './performance-fixture.ts';import {compare} from '../src/performance/schema.ts';
const hash='a'.repeat(64),artifact='artifact-11111111-1111-4111-8111-111111111111';
export function viewFixture():ProductReport{return {version:1,project:'/synthetic/evidence-demo',kind:'ml',ready:false,source:hash,spec:'b'.repeat(64),checks:[
 {id:'specification',status:'passed',detail:'Synthetic fixture: approved product scope.'},
 {id:'implementation',status:'passed',detail:'Tasks complete; this does not prove readiness.'},
 {id:'runtime:linux',status:'passed',detail:'Retained packaged GUI journey matches this source.',evidence:{version:1,id:'runtime:linux',provider:'linux-electron',approval:'journey-11111111-1111-4111-8111-111111111111',approvalDigest:hash,runtime:hash,required:true,subject:{kind:'application',digest:hash},applicability:'current',outcome:'passed',producer:'desktop-11111111-1111-4111-8111-111111111111',artifacts:[{id:artifact,name:'packaged-app.asar',sha256:hash}],detail:'Retained journey',limitations:['Human interaction review remains separate.'],next:'harness desktop list'}},
 {id:'ml:torch:quality',status:'passed',detail:'Host-computed held-out quality; no protected rows displayed.',evidence:{version:1,id:'ml:torch:quality',provider:'torch-cpu',approval:'torch-11111111-1111-4111-8111-111111111111',approvalDigest:hash,runtime:hash,required:true,subject:{kind:'model',digest:hash},applicability:'current',outcome:'passed',producer:'job-11111111-1111-4111-8111-111111111111',artifacts:[],metrics:[{name:'Classification error',value:.05,unit:'fraction',threshold:.15,comparison:'at-most',baseline:.5,samples:20}],lineage:{model:hash,train:hash,holdout:hash,preprocessing:hash,recipe:hash},detail:'Protected evaluation',limitations:['Dataset suitability remains human review.'],next:'harness torch list'}},
 {id:'ml:torch:checkpoint',status:'passed',detail:'Complete model/optimizer/RNG checkpoint.'},
 {id:'ml:torch:recovery',status:'stale',detail:'Recovery evidence needs a matching interruption and resumed attempt.',next:'harness torch list'},
 {id:'ml:torch:integration',status:'unavailable',detail:'Application integration is a separate evidence obligation.',next:'harness product report'},
 {id:'security',status:'accepted-risk',detail:'Prototype Origin risk explicitly accepted; not passed testing.'},
 {id:'performance',status:'passed',detail:'Current bounded benchmark meets approved limits.'},
 {id:'human-assessment',status:'human',detail:'Review interaction, dataset suitability and remaining limits.',next:'harness product assess'}
 ],security:{version:1,status:'accepted-risk',configured:true,complete:true,source:hash,scope:hash,run:'security-run-11111111-1111-4111-8111-111111111111',evidenceDigest:hash,requirements:[{id:'probes',status:'accepted-risk',detail:'Approved prototype limitation.'}],findings:[{rule:'origin',severity:'medium',summary:'Foreign Origin accepted.',remediation:'Validate the authorized Origin.',subject:hash,scope:hash,evidence:{run:'security-run-11111111-1111-4111-8111-111111111111',artifact},disposition:'accepted-risk',rationale:'Synthetic local prototype only; no release approval.'}],limitations:['No vulnerability feed or comprehensive security claim.'],next:'harness product report'},performance:{version:1,status:'passed',configured:true,complete:true,source:hash,scope:hash,run:'performance-run-11111111-1111-4111-8111-111111111111',artifact,environment,profile:{...profile,expectedJson:{secret:'NEVER_RENDER_APPROVED_RESPONSE'}},metrics:compare(profile,observation()).metrics,assessment:'passed',failures:[],detail:'Repeated local API timings.',limitations:['Sequential laptop/VM measurements; not production capacity.'],next:'harness product report'}};}
