import {randomUUID} from 'node:crypto';import {readdir} from 'node:fs/promises';import path from 'node:path';
import {stateRoot,safeDirectory,readJson,saveJson,sha256} from '../../artifacts/store.ts';
import {parseMacJourney} from './schema.ts';import type {Journey,Assessment} from '../../desktop/schema.ts';import type {readGuiRuntime} from './provision.ts';
export type GuiRuntime=Awaited<ReturnType<typeof readGuiRuntime>>;
export interface GuiApproval {version:1;id:string;at:string;journey:Journey;runtime:GuiRuntime;digest:string;}
export interface GuiRun {version:1;id:string;approval:string;approvalDigest:string;runtime:GuiRuntime;at:string;controllerPid:number;status:'preparing'|'running'|'passed'|'failed'|'interrupted';message:string;source?:string;artifacts:string[];nativeRun?:string;assessment?:Assessment;}
const valid=(id:string,prefix:string)=>{if(!new RegExp(`^${prefix}-[a-f0-9-]{36}$`,'u').test(id))throw Error('Invalid macOS GUI record ID.');};
export async function guiState(project:string){const root=path.join(await stateRoot(project),'macos-gui');await safeDirectory(root);await safeDirectory(root+'/approvals');await safeDirectory(root+'/runs');return root;}
export async function guiRunRoot(project:string,id:string){valid(id,'macos');const root=(await guiState(project))+'/runs/'+id;await safeDirectory(root);return root;}
export async function approveGui(project:string,raw:unknown,runtime:GuiRuntime){const content={version:1 as const,id:'macos-check-'+randomUUID(),at:new Date().toISOString(),journey:parseMacJourney(raw),runtime};const value={...content,digest:sha256(JSON.stringify(content))};await saveJson(await guiState(project),'approvals/'+value.id+'.json',value);return value;}
export async function readGuiApproval(project:string,id:string):Promise<GuiApproval>{valid(id,'macos-check');const a=await readJson(await guiState(project),'approvals/'+id+'.json') as GuiApproval;const {digest,...content}=a;if(a.version!==1||a.id!==id||digest!==sha256(JSON.stringify(content)))throw Error('macOS GUI approval changed.');parseMacJourney(a.journey);return a;}
export async function listGuiApprovals(project:string){const root=await guiState(project),result:GuiApproval[]=[];for(const f of await readdir(root+'/approvals'))if(/^macos-check-[a-f0-9-]{36}\.json$/u.test(f))result.push(await readGuiApproval(project,f.slice(0,-5)));return result.sort((a,b)=>a.at.localeCompare(b.at));}
export async function saveGuiRun(project:string,r:GuiRun){await saveJson(await guiRunRoot(project,r.id),'state.json',r);}
export async function readGuiRun(project:string,id:string):Promise<GuiRun>{valid(id,'macos');const r=await readJson(await guiRunRoot(project,id),'state.json') as GuiRun;if(r.version!==1||r.id!==id||!Number.isSafeInteger(r.controllerPid)||!['preparing','running','passed','failed','interrupted'].includes(r.status)||!Array.isArray(r.artifacts)||r.artifacts.some(a=>!/^artifact-[a-f0-9-]{36}$/u.test(a)))throw Error('Invalid macOS GUI record.');return r;}
export async function listGuiRuns(project:string){const root=await guiState(project),result:GuiRun[]=[];for(const id of await readdir(root+'/runs'))if(/^macos-[a-f0-9-]{36}$/u.test(id))result.push(await readGuiRun(project,id));return result.sort((a,b)=>a.at.localeCompare(b.at));}
