import {readFile} from 'node:fs/promises';import path from 'node:path';
import {fingerprint,hash,predict,assessPredictions} from '../../ml/schema.ts';import {validateCheckpoint,trainingInput,type Checkpoint} from '../../metal/schema.ts';import {resources} from '../../metal/runtime.ts';import {protocolHash} from '../../native/provision.ts';import type {MetalApproval} from '../../metal/store.ts';
import {parseNativeCheck,assessNative} from '../../native/schema.ts';import {object,uuidId,timestamp,type EvidenceRecord} from './schema.ts';import {same,ref,regressionMetrics,type MlData} from './ml.ts';import {EvidenceReader} from './reader.ts';
export async function metalQuality(reader:EvidenceReader,d:MlData,q:EvidenceRecord,c:EvidenceRecord,recovery:EvidenceRecord){
 const a=d.a as MetalApproval,s=d.state;
 if(a.runtime.profile.protocol!==await protocolHash())throw Error('Native protocol changed.');
 if(!Array.isArray(s.attempts)||!s.attempts.length||s.attempts.length>a.spec.limits.maxAttempts||s.attempts.length*a.spec.limits.timeoutSeconds>a.spec.limits.totalSeconds)throw Error('Invalid Metal attempt budget.');
 let completed=0,prior:Checkpoint|null=null,interrupted=false,demonstrated=false;
 for(const [i,raw]of s.attempts.entries()){
  const t=object(raw,['index','from','to','status']);if(t.index!==i+1||t.from!==completed||t.to!==Math.min(completed+a.spec.checkpointEvery,a.spec.epochs)||!['completed','interrupted'].includes(String(t.status)))throw Error('Metal attempt progress changed.');
  const namespace=`${d.folder}/segment-${i+1}-harness/`,runs=await reader.names(namespace+'native/runs');
  if(t.status==='interrupted'&&runs.length===0){interrupted=false;continue;}
  if(runs.length!==1||!uuidId(runs[0],'native'))throw Error('Missing or ambiguous Metal native segment.');const id=runs[0]!;
  const n=object(await reader.json(namespace+'native/runs/'+id+'/state.json'),['version','id','token','approval','profileDigest','status','message','at','artifacts','source','outputMounted','vmStarted','controllerPid']) as any;
  if(n.version!==1||n.id!==id||!uuidId(n.approval,'native-check')||n.profileDigest!==fingerprint(a.runtime.profile)||!timestamp(n.at)||n.outputMounted!==false||!['passed','failed','interrupted'].includes(n.status)||!Array.isArray(n.artifacts)||n.artifacts.length>40||new Set(n.artifacts).size!==n.artifacts.length)throw Error('Native segment identity or cleanup changed.');
  if(t.status==='interrupted'){if(!['failed','interrupted'].includes(n.status))throw Error('Metal interruption differs from underlying run.');interrupted=n.vmStarted===true&&completed>0;continue;}
  if(n.status!=='passed'||n.vmStarted!==true)throw Error('Native segment did not complete.');
  const approval=object(await reader.json(namespace+'native/approvals/'+n.approval+'.json'),['version','id','at','check','profileDigest','digest']),{digest,...body}=approval;
  if(approval.version!==1||approval.id!==n.approval||approval.profileDigest!==n.profileDigest||!timestamp(approval.at)||digest!==fingerprint(body))throw Error('Native segment approval changed.');
  same(parseNativeCheck(approval.check),{version:1,title:a.spec.title,entry:'run.sh',timeoutSeconds:a.spec.limits.timeoutSeconds,expectedExit:0,stdout:'Metal checkpoint ready\n',artifacts:['checkpoint.json']},'Native training command changed.');
  // The fixed segment source is reconstructible without executing Swift or exposing rows.
  const files:Record<string,string>={'input.json':hash(JSON.stringify(trainingInput(a,d.train,prior,Number(t.to)))),'package.json':hash('{"name":"harness-metal-training","private":true}')};for(const name of ['train.swift','run.sh'])files[name]=hash(await readFile(path.join(resources,name)));
  if(n.source!==fingerprint(Object.entries(files).sort(([a],[b])=>a.localeCompare(b))))throw Error('Native segment training inputs changed.');
  const artifacts=new Map<string,Awaited<ReturnType<EvidenceReader['artifact']>>>();for(const aid of n.artifacts){const v=await reader.artifact(aid,namespace);if(v.artifact.producer!==id||v.artifact.input!==n.source||v.artifact.environment!==n.profileDigest||artifacts.has(v.artifact.name))throw Error('Native segment artifact provenance changed.');artifacts.set(v.artifact.name,v);}
  const stdout=artifacts.get('stdout.txt'),assessment=artifacts.get('assessment.json'),point=artifacts.get('checkpoint.json');if(!stdout||!assessment||!point)throw Error('Missing native segment observations.');
  const obs=object(JSON.parse(assessment.bytes.toString()),['passed','expectedExit','observedExit','stdoutMatches']);if(!Number.isInteger(obs.observedExit)||!assessNative(parseNativeCheck(approval.check),{exit:obs.observedExit,stdout:stdout.bytes.toString()}).passed)throw Error('Native segment did not meet its command contract.');
  prior=validateCheckpoint(JSON.parse(point.bytes.toString()),a,completed,Number(t.to),prior?.device);completed=Number(t.to);c.artifacts.push(ref(point));q.at=n.at;if(interrupted)demonstrated=true;interrupted=false;
 }
 if(completed!==a.spec.epochs||!prior||s.checkpointHash!==fingerprint(prior)||s.evaluatedHash!==fingerprint(prior.model))throw Error('Metal final checkpoint identity changed.');same(s.checkpoint,prior,'Metal checkpoint differs from executed segment.');
 const score=assessPredictions(d.holdout.map(r=>predict(prior!.model,r.x)),d.holdout.map(r=>r.y),a.baseline,a.spec);same(s.assessment,score,'Evaluation score changed.');if(s.status!==(score.passed?'passed':'failed'))throw Error('Evaluation status changed.');
 if(score.passed){const v=await reader.artifact(s.artifact),f=v.artifact;if(f.name!=='metal-model.json'||f.producer!==a.id||f.input!==a.digest||f.environment!==fingerprint(a.runtime)||f.verification!=='evaluation-passed'||f.evaluation?.approval!==a.digest||f.evaluation.reportHash!==fingerprint(score))throw Error('Evaluated model provenance changed.');same(JSON.parse(v.bytes.toString()),prior.model,'Evaluated model differs from final checkpoint.');q.artifacts.push(ref(v));}
 q.subject={kind:'model',digest:s.evaluatedHash};q.producer=a.id;q.lineage={model:s.evaluatedHash,train:a.trainHash,holdout:a.holdoutHash,preprocessing:fingerprint(a.preprocessing),recipe:a.runtime.protocol};q.metrics=regressionMetrics(score,a.spec,d.holdout.length);q.applicability='current';q.outcome=score.passed?'passed':'failed';q.detail=`Metal holdout RMSE ${score.rmse}; ceiling ${a.spec.maxRmse}, baseline ${score.baselineRmse}, ${d.holdout.length} held-out rows. Executed device: ${prior.device}.`;q.limitations.push('Fixed float32 regression; GPU time is not exclusively allocated and no performance claim is made.');
 c.subject=q.subject;c.lineage=q.lineage;c.applicability='current';c.outcome='passed';c.detail='All completed native segments match approved training inputs; final numeric checkpoint matches evaluation.';
 recovery.subject=q.subject;recovery.lineage=q.lineage;if(demonstrated){recovery.applicability='current';recovery.outcome=q.outcome;recovery.artifacts=c.artifacts;recovery.detail='An interrupted owned VM segment was cleaned up; a later segment resumed the prior completed checkpoint and produced this evaluated model. In-flight epochs are rerun; no uninterrupted-reference equivalence is claimed.';}
}
