import {fingerprint} from '../../ml/schema.ts';import type {TorchApproval} from '../../torch/store.ts';import {assessTorch,predictTorch,validateTorchModel,validateTorchCheckpoint} from '../../torch/schema.ts';
import type {Job} from '../../jobs/state.ts';import {validateCheckpoint} from '../../jobs/schema.ts';import {object,type EvidenceRecord} from './schema.ts';import {same,ref,type MlData} from './ml.ts';import {EvidenceReader} from './reader.ts';
export async function torchQuality(reader:EvidenceReader,d:MlData,j:Job,m:Awaited<ReturnType<EvidenceReader['artifact']>>,cp:Awaited<ReturnType<EvidenceReader['artifact']>>,q:EvidenceRecord){
 const a=d.a as TorchApproval,s=d.state,model=validateTorchModel(JSON.parse(m.bytes.toString()),a.features.length,a.spec.clusters);
 if(model.context!==a.digest||model.kind!==a.spec.kind||model.completed!==a.spec.steps||s.candidateHash!==m.artifact.sha256)throw Error('Model does not match approved training.');
 const point=validateCheckpoint(cp.bytes,j.spec.checkpoint!,j.identity!,a.spec.steps),p=point.payload as any;validateTorchCheckpoint(p,a.digest,a.spec.steps,a.spec.kind);
 if(p.runtime!=='2.14.0+cpu')throw Error('PyTorch checkpoint runtime changed.');
 if(a.spec.kind==='classifier'){
  const weights:Record<string,unknown>={};if(!p.model||Object.keys(p.model).join()!=='dict'||!Array.isArray(p.model.dict))throw Error('Invalid checkpoint model encoding.');
  for(const pair of p.model.dict){if(!Array.isArray(pair)||pair.length!==2||typeof pair[0]!=='string'||Object.hasOwn(weights,pair[0]))throw Error('Invalid checkpoint tensor name.');const t=object(pair[1],['tensor','dtype']);if(t.dtype!=='float32')throw Error('Invalid checkpoint tensor type.');weights[pair[0]]=t.tensor;}
  same(weights,model.weights,'Checkpoint weights differ from evaluated model.');if(p.permutation.length!==d.train.length)throw Error('Checkpoint sampler does not cover the training set.');
 }else same(p.centers,model.centers,'Checkpoint centers differ from evaluated model.');
 const values=predictTorch(model,d.holdout,a.means,a.scales),score=assessTorch(a.spec.kind,values,d.holdout.map(r=>r.y??0),a.spec.maxError);
 const majority=Number(d.train.filter(r=>r.y===1).length>d.train.length/2),baseline=a.spec.kind==='classifier'?d.holdout.filter(r=>r.y!==majority).length/d.holdout.length:d.holdout.reduce((sum,r)=>sum+r.x.reduce((v,x,i)=>v+((x-a.means[i]!)/a.scales[i]!)**2,0),0)/d.holdout.length;
 const expected={...score,baseline,passed:score.passed&&score.error<baseline,rows:d.holdout.length,candidateHash:s.candidateHash,limitation:a.spec.kind==='kmeans'?'Distance measures compactness, not useful semantic groups.':'Small binary numeric classifier; generalization depends on representative independent rows.'};
 same(s.report,expected,'Evaluation score changed.');if(s.status!==(expected.passed?'passed':'failed'))throw Error('Evaluation status changed.');
 if(expected.passed){const v=await reader.artifact(s.artifact),f=v.artifact;if(f.name!=='torch-model.json'||f.producer!==a.id||f.input!==a.digest||f.environment!==j.identity||f.verification!=='evaluation-passed'||f.evaluation?.approval!==a.digest||f.evaluation.reportHash!==fingerprint(expected))throw Error('Evaluated model provenance changed.');same(JSON.parse(v.bytes.toString()),{...model,features:a.features,means:a.means,scales:a.scales},'Evaluated model differs from training output.');q.artifacts.push(ref(v));}
 q.subject={kind:'model',digest:m.artifact.sha256};q.applicability='current';q.outcome=expected.passed?'passed':'failed';q.metrics=[{name:score.metric,value:score.error,unit:a.spec.kind==='classifier'?'fraction misclassified':'squared standardized feature units',threshold:a.spec.maxError,comparison:'at-most',baseline,samples:d.holdout.length}];q.detail=`${score.metric}: ${score.error}; ceiling ${a.spec.maxError}, baseline ${baseline}, ${d.holdout.length} held-out rows. Host comparison ${q.outcome}.`;q.limitations.push(expected.limitation);q.lineage={model:m.artifact.sha256,train:a.trainHash,holdout:a.holdoutHash,preprocessing:fingerprint({means:a.means,scales:a.scales}),recipe:a.recipe,trainingSource:j.source!.digest};
}
