import {randomUUID} from 'node:crypto';import path from 'node:path';import {readdir} from 'node:fs/promises';
import {stateRoot,safeDirectory,readJson,saveJson,sha256} from '../artifacts/store.ts';
import {parseNativeCheck,type NativeCheck} from './schema.ts';import type {NativeProfile} from './provision.ts';
export interface NativeApproval {version:1;id:string;at:string;check:NativeCheck;profileDigest:string;digest:string;}
export interface NativeRun {version:1;id:string;token:string;approval:string;profileDigest:string;status:'preparing'|'running'|'passed'|'failed'|'interrupted';message:string;at:string;artifacts:string[];source?:string;outputMounted:boolean;vmStarted?:boolean;controllerPid?:number;}
const id=(value:string,prefix:string)=>{if(!new RegExp(`^${prefix}-[a-f0-9-]{36}$`,'u').test(value))throw Error('Invalid native record ID.');};
export async function nativeState(project:string){const root=path.join(await stateRoot(project),'native');await safeDirectory(root);await safeDirectory(root+'/approvals');await safeDirectory(root+'/runs');return root;}
export async function nativeRunRoot(project:string,value:string){id(value,'native');const root=path.join(await nativeState(project),'runs',value);await safeDirectory(root);return root;}
export async function approveNative(project:string,raw:unknown,profile:NativeProfile){const content={version:1 as const,id:`native-check-${randomUUID()}`,at:new Date().toISOString(),check:parseNativeCheck(raw),profileDigest:sha256(JSON.stringify(profile))};const a={...content,digest:sha256(JSON.stringify(content))};await saveJson(await nativeState(project),'approvals/'+a.id+'.json',a);return a;}
export async function readNativeApproval(project:string,value:string):Promise<NativeApproval>{id(value,'native-check');const a=await readJson(await nativeState(project),'approvals/'+value+'.json') as NativeApproval;const {digest,...content}=a;if(a.version!==1||a.id!==value||digest!==sha256(JSON.stringify(content)))throw Error('Native approval changed.');parseNativeCheck(a.check);return a;}
export async function listNativeApprovals(project:string){const root=await nativeState(project),all:NativeApproval[]=[];for(const f of await readdir(root+'/approvals'))if(/^native-check-[a-f0-9-]{36}\.json$/u.test(f))all.push(await readNativeApproval(project,f.slice(0,-5)));return all.sort((a,b)=>a.at.localeCompare(b.at));}
export async function saveNativeRun(project:string,r:NativeRun){await saveJson(await nativeRunRoot(project,r.id),'state.json',r);}
export async function readNativeRun(project:string,value:string):Promise<NativeRun>{const r=await readJson(await nativeRunRoot(project,value),'state.json') as NativeRun;if(r.version!==1||r.id!==value||!/^[-a-f0-9]{36}$/u.test(r.token)||!['preparing','running','passed','failed','interrupted'].includes(r.status)||typeof r.outputMounted!=='boolean'||!Array.isArray(r.artifacts)||r.artifacts.some(a=>!/^artifact-[a-f0-9-]{36}$/u.test(a)))throw Error('Invalid native run record.');return r;}
export async function listNativeRuns(project:string){const root=await nativeState(project),all:NativeRun[]=[];for(const f of await readdir(root+'/runs'))if(/^native-[a-f0-9-]{36}$/u.test(f))all.push(await readNativeRun(project,f));return all.sort((a,b)=>a.at.localeCompare(b.at));}
