import {countLeaks as count,creationLeaks} from './scan.mjs';
// Only this observer can access the request/outputs mounts. The app shares its network, not its filesystem.
import {readFile,writeFile} from 'node:fs/promises';import {randomBytes} from 'node:crypto';import http from 'node:http';
const r=JSON.parse(await readFile('/harness-checks/request.json','utf8')),origin=`http://127.0.0.1:${r.port}`;
function request(path,method='GET',body,headers={}){return new Promise((resolve,reject)=>{let size=0;const req=http.request(origin+path,{method,headers:{Origin:origin,...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},timeout:3000},res=>{const parts=[];res.on('data',b=>{size+=b.length;if(size>65536){res.destroy();reject(Error('response-limit'));}else parts.push(b);});res.on('error',reject);res.on('end',()=>{const body=Buffer.concat(parts).toString();let data;try{data=JSON.parse(body);}catch{}resolve({status:res.statusCode,body,data,headers:JSON.stringify(res.rawHeaders),all:JSON.stringify(res.rawHeaders)+'\n'+body+'\n'+(data===undefined?'':JSON.stringify(data))});});});req.on('timeout',()=>req.destroy(Error('request-timeout')));req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});}
try{
 let ready;const deadline=Date.now()+Math.min(30000,r.timeoutSeconds*500);while(Date.now()<deadline){try{ready=await request(r.publicPath);break;}catch{await new Promise(res=>setTimeout(res,200));}}if(!ready)throw Error('startup');
 const markers=[0,1].map(()=>`HARNESS_SYNTHETIC_${randomBytes(18).toString('hex')}`),keys=[],creates=[];
 for(let i=0;i<2;i++){const body=Object.fromEntries(Object.entries(r.fields).map(([k,v])=>[k,typeof v==='string'?v.replaceAll('$MARKER',markers[i]):v])),res=await request(r.createPath,'POST',body);const key=res.data?.[r.keyField];if(typeof key!=='string'||key.length<16||key.length>4096)throw Error('missing-key');keys.push(key);creates.push(res);}
 const responses=[];for(const key of keys)responses.push(await request(r.privatePath,'GET',undefined,{Authorization:'Bearer '+key}));
 const missing=await request(r.privatePath),invalid=await request(r.privatePath,'GET',undefined,{Authorization:'Bearer HARNESS_INVALID_'+randomBytes(16).toString('hex')}),foreign=await request(r.privatePath,'GET',undefined,{Origin:'http://unapproved.invalid',Authorization:'Bearer '+keys[0]}),host=await request(r.privatePath,'GET',undefined,{Host:'unapproved.invalid',Authorization:'Bearer '+keys[0]}),media=await request(r.createPath,'POST',r.fields,{'Content-Type':'text/plain'}),publicAfter=await request(r.publicPath);
 let keyLeaks=count(ready.all,keys);for(const [i,res]of creates.entries()){keyLeaks+=creationLeaks(res.headers,res.body,keys[i],keys);}
 for(const res of [...responses,missing,invalid,foreign,host,media,publicAfter])keyLeaks+=count(res.all,keys);
 const privateLeaks=[missing,invalid,foreign,host,...(r.pendingPrivate?[publicAfter]:[])].reduce((n,res)=>n+count(res.all,markers),0);
 const observations={version:1,statuses:{public:ready.status,create1:creates[0].status,create2:creates[1].status,authorized1:responses[0].status,authorized2:responses[1].status,missing:missing.status,invalid:invalid.status,origin:foreign.status,host:host.status,media:media.status,publicAfter:publicAfter.status},keysDistinct:keys[0]!==keys[1],ownMarkers:responses.map((res,i)=>count(res.all,[markers[i]])),otherMarkers:responses.map((res,i)=>count(res.all,[markers[1-i]])),keyLeaks,privateLeaks};
 await writeFile('/work/observations.json',JSON.stringify(observations));await writeFile('/work/synthetic-secrets.json',JSON.stringify({keys,markers}),{mode:0o600});
}catch{console.error('Security probe incomplete; no raw response or credential retained in diagnostics.');process.exitCode=1;}
