import {randomUUID} from 'node:crypto';import {readdir} from 'node:fs/promises';import path from 'node:path';
import {stateRoot,safeDirectory,readJson,saveJson,sha256} from '../../artifacts/store.ts';
import {parseAppleJourney} from './schema.ts';import type {Assessment} from '../../desktop/schema.ts';import type {AppleJourney} from './schema.ts';import type {readAppleRuntime} from './runtime.ts';
export type AppleRuntime=Awaited<ReturnType<typeof readAppleRuntime>>;
export interface AppleApproval {version:1;id:string;at:string;journey:AppleJourney;runtime:AppleRuntime;digest:string;}
export interface AppleRun {version:1;id:string;approval:string;approvalDigest:string;runtime:AppleRuntime;at:string;controllerPid:number;status:'preparing'|'running'|'passed'|'failed'|'interrupted';message:string;source?:string;artifacts:string[];nativeRun?:string;assessment?:Assessment;}
const valid=(id:string,prefix:string)=>{if(!new RegExp(`^${prefix}-[a-f0-9-]{36}$`,'u').test(id))throw Error('Invalid native UI record ID.');};
export async function appleState(project:string){const root=path.join(await stateRoot(project),'apple-gui');await safeDirectory(root);await safeDirectory(root+'/approvals');await safeDirectory(root+'/runs');return root;}
export async function appleRunRoot(project:string,id:string){valid(id,'apple');const root=(await appleState(project))+'/runs/'+id;await safeDirectory(root);return root;}
export async function approveApple(project:string,raw:unknown,runtime:AppleRuntime){const content={version:1 as const,id:'apple-check-'+randomUUID(),at:new Date().toISOString(),journey:parseAppleJourney(raw),runtime};const value={...content,digest:sha256(JSON.stringify(content))};await saveJson(await appleState(project),'approvals/'+value.id+'.json',value);return value;}
export async function readAppleApproval(project:string,id:string):Promise<AppleApproval>{valid(id,'apple-check');const a=await readJson(await appleState(project),'approvals/'+id+'.json') as AppleApproval;const {digest,...content}=a;if(a.version!==1||a.id!==id||digest!==sha256(JSON.stringify(content)))throw Error('native UI approval changed.');parseAppleJourney(a.journey);return a;}
export async function listAppleApprovals(project:string){const root=await appleState(project),result:AppleApproval[]=[];for(const f of await readdir(root+'/approvals'))if(/^apple-check-[a-f0-9-]{36}\.json$/u.test(f))result.push(await readAppleApproval(project,f.slice(0,-5)));return result.sort((a,b)=>a.at.localeCompare(b.at));}
export async function saveAppleRun(project:string,r:AppleRun){await saveJson(await appleRunRoot(project,r.id),'state.json',r);}
export async function readAppleRun(project:string,id:string):Promise<AppleRun>{valid(id,'apple');const r=await readJson(await appleRunRoot(project,id),'state.json') as AppleRun;if(r.version!==1||r.id!==id||!Number.isSafeInteger(r.controllerPid)||!['preparing','running','passed','failed','interrupted'].includes(r.status)||!Array.isArray(r.artifacts)||r.artifacts.some(a=>!/^artifact-[a-f0-9-]{36}$/u.test(a)))throw Error('Invalid native UI record.');return r;}
export async function listAppleRuns(project:string){const root=await appleState(project),result:AppleRun[]=[];for(const id of await readdir(root+'/runs'))if(/^apple-[a-f0-9-]{36}$/u.test(id))result.push(await readAppleRun(project,id));return result.sort((a,b)=>a.at.localeCompare(b.at));}
