import {escape,diffBlock,type QueueItem,type RunView} from './render.ts';
import type {TeamView} from './status.ts';
import {emptyWorkspace,type WorkspaceInfo} from './workspace.ts';
export interface Action {title:string;message:string;command:string;href:string;}
const quote=(s:string)=>"'"+s.replaceAll("'","'\\''")+"'";
export function nextAction(items:readonly QueueItem[],teams:readonly TeamView[],runs:readonly RunView[],data:WorkspaceInfo):Action{
 const make=(title:string,message:string,command:string,href:string):Action=>({title,message,command,href});
 if(data.warnings.length)return make('Project data needs attention',data.warnings[0]!,'harness doctor','#attention');
 if(data.ordinary?.reason)return make('Inspect the stopped run',data.ordinary.reason,'harness guide','#attention');
 if(data.ordinary?.live||teams.some(t=>t.live))return make('Work is in progress','Select an agent to inspect its current assignment and recorded activity.','harness look','#office');
 if(data.plan?.status==='interrupted'||data.plan?.error)return make('Resume the saved plan',data.plan.error??'Your planning documents are retained. Continue from the saved conversation.','harness plan resume','#journey');
 const stopped=teams.find(t=>/interrupted|recover|stopped|aborting|applying/.test(t.status)&&!t.live);
 if(stopped)return make('Review the interrupted team',stopped.reason??'Inspect the saved team before resuming or recovering it.',`harness team inspect ${quote(stopped.runId)}`,'#attention');
 const staged=teams.find(t=>t.status==='staged');if(staged)return make('Review staged changes','The candidate is retained; project files have not been updated.',`harness team inspect ${quote(staged.runId)}`,'#review');
 if(data.plan?.status==='running')return make('Planning is in progress','The latest saved planning documents are available below.','harness plan status','#journey');
 if(data.plan&&data.plan.phase==='draft')return make('Review the saved plan','Read the draft and decisions before approving the scope.','harness plan review','#journey');
 if(data.plan&&data.plan.phase==='items')return make('Continue generating tasks','The approved plan is saved; resume automatic task generation.','harness plan resume','#journey');
 if(!items.length)return make(data.plan?.phase==='ready'?'Import the planned tasks':'Start a planning interview',data.plan?.phase==='ready'?'Review the generated items, then continue through the guide.':'No tasks yet. Your answers and documents will carry forward into the build.','harness guide','#journey');
 const next=items.find(i=>i.next&&i.feature.priority!=='wont');
 const open=items.filter(i=>i.feature.priority!=='wont'&&i.feature.status!=='done');
 if(open.length&&(!data.approval||next&&!data.approval.manifest.cases.some(c=>c.tasks.includes('*')||c.tasks.includes(next.feature.id))))return make('Approve acceptance checks','Define the behaviour the harness should independently check before applying work.','harness checks setup','#journey');

 const blocked=open.find(i=>/blocked|error|failed|escalated|revalidation/.test(i.state));
 if(blocked){const last=runs.find(r=>r.run.goal===blocked.feature.id);return make('Resolve the task that needs you',last?.run.requestedInput??last?.run.reason??`${blocked.feature.title}: ${blocked.state}`,'harness guide','#attention');}
 if(next)return make(`Next task: ${next.feature.title}`,'Read its acceptance criteria, then use the guide to continue.','harness guide','#tasks');
 return make(open.length?'Review task prerequisites':'Review the completed work',open.length?'No task is ready; check which prerequisite needs to finish.':'Applied changes are separate from Git commits and publishing.','harness look',open.length?'#tasks':'#review');
}
export function commandButton(command:string,project?:string):string{const full=project?`cd ${quote(project)} && ${command}`:command;return `<span class="command-row"><code>${escape(full)}</code><button type="button" class="action" data-copy-command="${escape(full)}">Copy command</button></span>`;}
const list=(values:readonly string[],empty='Not recorded')=>values.length?`<ul>${values.map(v=>`<li>${escape(v)}</li>`).join('')}</ul>`:`<p class="meta">${escape(empty)}</p>`;
export function workspacePanels(items:readonly QueueItem[],teams:readonly TeamView[],runs:readonly RunView[],data:WorkspaceInfo=emptyWorkspace(),live=false,project?:string){
 const action=nextAction(items,teams,runs,data),attention:{title:string;body:string;href:string}[]=[];
 if(data.ordinary?.reason)attention.push({title:'Run stopped updating',body:data.ordinary.reason,href:'#office'});
 for(const w of data.warnings)attention.push({title:'Saved data unavailable',body:w,href:'#journey'});
 if(data.plan&&(data.plan.status==='interrupted'||data.plan.phase==='draft'||data.plan.error))attention.push({title:data.plan.error?'Planning needs attention':'Plan awaiting your review',body:data.plan.error??data.plan.topic,href:'#journey'});
 if(items.some(i=>i.feature.priority!=='wont'&&i.feature.status!=='done')&&(!data.approval||items.some(i=>i.next&&!data.approval!.manifest.cases.some(c=>c.tasks.includes('*')||c.tasks.includes(i.feature.id)))))attention.push({title:'Acceptance checks need approval',body:'The next task needs approved acceptance coverage. A draft or passing project test does not provide that approval.',href:'#journey'});
 for(const i of items.filter(i=>i.feature.priority!=='wont'&&i.feature.status!=='done'&&(i.waitingFor?.length||/blocked|error|failed|escalated|revalidation/.test(i.state)))){const run=runs.find(r=>r.run.goal===i.feature.id);attention.push({title:i.feature.title,body:run?.run.requestedInput??run?.run.reason??(i.waitingFor?.length?`Waiting for ${i.waitingFor.join(', ')}`:i.state),href:'#tasks'});}
 for(const t of teams.filter(t=>t.status==='staged'||/interrupted|stopped|recover|aborted/.test(t.status)))attention.push({title:t.status==='staged'?'Ready for staged review':`Team ${t.status}`,body:t.reason??t.runId,href:t.status==='staged'?'#review':'#teams'});
 for(const r of data.releases.filter(r=>['draft','staging'].includes(r.status)))attention.push({title:`Release ${r.status==='draft'?'needs approval':'needs recovery'}`,body:`${r.manifest.name} ${r.manifest.version}`,href:'#outputs'});
 const attentionHtml=`<section id="attention" class="section guidance-panel" data-workspace-section><div class="section-heading"><h2>Needs your attention</h2><span class="badge">${attention.length}</span></div>${attention.length?`<div class="attention-grid">${attention.map(a=>`<a class="attention-card" href="${a.href}"><strong>${escape(a.title)}</strong><span>${escape(a.body)}</span><small>View details →</small></a>`).join('')}</div>`:'<p class="meta">No recorded blockers or pending reviews.</p>'}</section>`;
 const latest=runs[0],steps=[['Plan',data.plan?`${data.plan.phase} · ${data.plan.status}`:'No saved interview','#planning-documents'],['Approve',data.approval?'Acceptance checks approved':'Acceptance approval not recorded','#planning-documents'],['Build',data.ordinary?.live||teams.some(t=>t.live)?'Work active':latest?`Latest run: ${latest.run.outcome}`:'No recorded run','#history'],['Verify',latest?.run.acceptance?'Acceptance proof recorded':latest?.run.gates.length?'Project checks recorded':'No proof recorded','#review'],['Review',teams.some(t=>t.status==='staged')?'Staged changes await your review':latest?.run.review?.verdict??'No review recorded','#review'],['Apply',teams.some(t=>t.status==='staged')?'Staged · not applied':runs.some(r=>r.standing&&r.run.outcome==='applied')?'Applied work recorded':'No applied work','#history']];
 const journey=`<section id="journey" class="section guidance-panel" data-workspace-section><div class="section-heading"><h2>Project journey</h2><p>Stages repeat for each task</p></div><ol class="journey-steps">${steps.map(([name,status,href],i)=>`<li><a href="${href}"><span>${i+1}</span><strong>${name}</strong><small>${escape(status!)}</small></a></li>`).join('')}</ol><p class="meta">${data.profile?`${escape(data.profile.adapter.id)} · ${escape(data.profile.runner.id)} · ${escape(data.profile.requirements.os)}`:'Project environment has not been saved.'}</p><details id="planning-documents" data-state-key="planning-documents"><summary>Saved plans, decisions and acceptance checks · ${data.documents.length}</summary>${data.documents.length?data.documents.map(d=>`<details data-state-key="doc-${escape(d.name)}"><summary>${escape(d.name)} <span class="badge">${escape(d.status)}</span></summary><pre class="document-text">${escape(d.text)}</pre></details>`).join(''):'<p class="empty">No saved planning documents yet.</p>'}</details></section>`;
 const reviews=`<section id="review" class="section guidance-panel" data-workspace-section><div class="section-heading"><h2>Review changes</h2><p>Evidence and proposed changes together</p></div>${data.reviews.map(r=>{const team=teams.find(t=>t.runId===r.id);return `<details data-state-key="review-${escape(r.id)}" class="review-card"><summary>${escape(r.id)} <span class="badge">${escape(r.status==='staged'?'Staged · not applied':r.status)}</span></summary><p>Comparison of the retained original source and team staging. Application rechecks the candidate before changing project files.</p>${team?.attempts.map(a=>`<article><h3>${escape(a.task)}</h3><h4>Acceptance criteria</h4>${list(team.tasks.find(t=>t.id===a.task)?.criteria??items.find(i=>i.feature.id===a.task)?.feature.criteria??[])}<p>Independent review: ${escape(a.review)} · Integration: ${escape(a.integration)}</p><h4>Project checks</h4>${list(a.gates)}<h4>Combined integration checks</h4>${list(a.integrationGates??[])}${list(a.findings??[],'No reviewer findings recorded.')}</article>`).join('')??''}${r.files.map(diffBlock).join('')||'<p>No changed files in the retained comparison.</p>'}</details>`;}).join('')}${runs.slice(0,12).map(v=>`<details data-state-key="run-review-${escape(v.run.id)}" class="review-card"><summary>${escape(v.title??v.run.goal)} · ${escape(v.run.id)} <span class="badge">${escape(v.run.outcome==='applied'&&!v.standing?'Reversed':v.run.outcome)}</span></summary><h3>Acceptance criteria</h3>${list(v.criteria)}<h3>Project checks</h3>${list(v.run.gates)}<h3>Operator-approved acceptance</h3><p>${v.run.acceptance?`Recorded proof · approval ${escape(v.run.acceptance.approvalDigest.slice(0,16))} · candidate ${escape(v.run.acceptance.candidateDigest.slice(0,16))}`:'No independent acceptance proof recorded for this run.'}</p><h3>Independent review</h3><p>${escape(v.run.review?.verdict??'Not recorded')}</p>${list(v.run.review?.findings??[],'No findings recorded.')}<h3>Changed files</h3>${v.files.map(diffBlock).join('')||'<p>No changed files.</p>'}<a href="#${escape(v.run.id)}">Open complete run record →</a></details>`).join('')}${!data.reviews.length&&!runs.length?'<p class="empty">Proposed changes and verification evidence will appear here after work runs.</p>':''}</section>`;
 const outputs=`<section id="outputs" class="section guidance-panel" data-workspace-section><div class="section-heading"><h2>Outputs & releases</h2><p>Retained artifacts · local staging</p></div><p class="meta">Verification labels describe recorded evidence; a download does not approve, apply or publish anything.</p>${data.outputs.map(a=>`<details class="output-card" data-state-key="output-${escape(a.id)}"><summary>${escape(a.name)} <span class="badge">${escape(a.verification)}</span></summary><p>${a.size.toLocaleString('en-GB')} bytes · Producer ${escape(a.producer)}</p><p class="team-id">${escape(a.id)}<br>SHA-256 ${a.sha256}</p>${a.preview?`<img class="output-preview" src="${a.preview}" alt="Retained screenshot ${escape(a.name)}">`:''}${live&&a.size<=32*1024*1024?`<a class="action" href="/output/${a.id}" download="${escape(a.name.split('/').at(-1)!)}">Download retained output</a>`:'<p>Use the project terminal to export. Browser downloads require a live viewer and outputs of 32 MiB or less.</p>'}${commandButton(`harness artifacts inspect ${quote(a.id)}`,project)}</details>`).join('')||'<p class="empty">No retained outputs. Use harness verify --retain or a saved job to retain results.</p>'}${data.releases.map(r=>`<article class="release-card"><h3>${escape(r.manifest.name)} · ${escape(r.manifest.version)}</h3><span class="badge">${escape(r.status)}</span><p>${r.status==='staged'?'Staged locally; not published remotely.':'Local release preparation.'}</p><p class="team-id">${escape(r.manifest.target)}</p>${r.reason?`<p>${escape(r.reason)}</p>`:''}${commandButton('harness guide',project)}</article>`).join('')}</section>`;
 const orbit=`<section id="orbit-guidance" class="guidance-panel orbit-panel" data-workspace-section><div class="section-heading"><h2>Orbit’s guidance</h2><a href="#office">Back to the office ↑</a></div><p class="meta">Based on saved harness state. Orbit does not start work or make model calls.</p><h3>${escape(action.title)}</h3><p>${escape(action.message)}</p><a href="${action.href}">See the relevant details →</a>${commandButton(action.command,project)}</section>`;
 return {attention:attentionHtml,journey,review:reviews,outputs,orbit};
}
export const GUIDANCE_STYLE=`
.guidance-panel{padding:1.1rem 1.3rem;background:var(--card);border:1px solid var(--line);border-radius:12px;margin:1rem 0}.guidance-panel .section-heading{margin:0 0 .8rem}.attention-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:.7rem}.attention-card{padding:.8rem;border:1px solid var(--line);border-left:3px solid var(--rev);border-radius:7px;text-decoration:none;display:grid;gap:.35rem;color:var(--fg)}.attention-card span{font-size:.85rem;color:var(--dim);overflow-wrap:anywhere}.attention-card small{color:var(--accent)}.journey-steps{padding:0;list-style:none;display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:.5rem}.journey-steps a{display:grid;gap:.3rem;padding:.65rem;text-decoration:none;border:1px solid var(--line);border-radius:8px;color:var(--fg)}.journey-steps span{font-size:.7rem;color:var(--accent)}.journey-steps small{color:var(--dim);font-size:.72rem}.document-text{white-space:pre-wrap;overflow-wrap:anywhere;max-height:450px;overflow:auto;font:12px/1.6 ui-monospace,monospace;background:var(--bg);padding:1rem}.review-card,.output-card{padding:.8rem 0}.review-card>summary,.output-card>summary{font:600 .9rem/1.5 system-ui;flex-wrap:wrap}.review-card article{border-bottom:1px solid var(--line);padding:.5rem}.output-preview{max-width:100%;max-height:350px;object-fit:contain}.release-card{border-top:1px solid var(--line);padding:1rem 0}.command-row{display:flex;align-items:center;gap:.6rem;flex-wrap:wrap;margin:.7rem 0}.command-row code{font-size:12px;overflow-wrap:anywhere;background:var(--bg);padding:.5rem}.orbit-panel h3{font-size:1rem;text-transform:none;color:var(--fg)}.office-hover{cursor:pointer;background:none;border:0;padding:0}.office-hover:focus-visible{outline:2px solid var(--accent)}.office-hover:focus-visible .companion-label{opacity:1}.office-controls{display:flex;align-items:center;gap:.4rem;flex-wrap:wrap}.office-controls button{padding:.4rem .6rem}.office-viewport{overflow:auto;max-height:75vh}.office-viewport .office-map{min-width:0}.office-person .avatar-name{visibility:hidden}.office-person:hover .avatar-name,.office-person:focus-visible .avatar-name,.office-person[aria-pressed=true] .avatar-name{visibility:visible}.office-inspector-hidden .office-layout{grid-template-columns:minmax(0,1fr)}.office-inspector-hidden .office-inspector{display:none}.office-expanded{position:fixed;inset:0;z-index:50;margin:0!important;padding:1rem;background:var(--bg);overflow:auto}.office-expanded .office-viewport{max-height:80vh}.office-expanded .office-layout{max-width:1600px;margin:auto}.office-expanded .office-map{min-width:900px}.office-controls label{font-size:12px;color:var(--dim)}.office-controls select{padding:.4rem}.office-section .office-layout{grid-template-columns:minmax(0,1fr) 225px}.office-inspector-hidden .office-layout{grid-template-columns:1fr}#overview{margin-top:1rem}.overview+.office-section{margin-top:1rem}.update-note{font-size:12px;color:var(--dim)}
@media(max-width:1000px){.journey-steps{grid-template-columns:repeat(3,1fr)}.office-section .office-layout{grid-template-columns:1fr}.office-inspector{border-left:0;border-top:1px solid var(--line)}.office-roster{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.journey-steps{grid-template-columns:repeat(2,1fr)}.guidance-panel{padding:1rem}.office-heading{align-items:flex-start}.office-controls{width:100%}}
`;

export function workspaceSections(...args:Parameters<typeof workspacePanels>):string{return Object.values(workspacePanels(...args)).join('');}
