import {escape} from './render.ts';
import {commandButton} from './guidance.ts';
import {verificationActions,checkTitle} from '../product/actions.ts';
import type {ProductReport} from '../product/report.ts';
import {uuidId} from '../product/evidence/schema.ts';
const labels:Record<string,string>={passed:'Passed',failed:'Failed',missing:'Missing evidence',stale:'Needs recheck',human:'Human review needed',unavailable:'Unavailable',skipped:'Skipped','accepted-risk':'Accepted risk'};
const badge=(s:string)=>`<span class="evidence-status evidence-${escape(s)}">${escape(labels[s]??s)}</span>`;
const textList=(items:readonly string[])=>`<ul>${items.map(s=>`<li>${escape(s)}</li>`).join('')}</ul>`;
const number=(n:number)=>Number.isFinite(n)?n.toLocaleString('en-GB',{maximumFractionDigits:3}):'Unavailable';
const identity=(name:string,value:string|undefined)=>value?`<dt>${escape(name)}</dt><dd class="evidence-id">${escape(value)}</dd>`:'';
function output(id:string,name:string,live:boolean,project?:string){return `<li>${escape(name)}<span class="evidence-id">${escape(id)}</span>${live&&uuidId(id,'artifact')?`<a href="/output/${id}" download>Download verified retained bytes</a>`:''}${uuidId(id,'artifact')?commandButton('harness artifacts inspect '+id,project):''}</li>`;}
export function productEvidence(report:ProductReport|undefined,error:string|undefined,live=false,project?:string):string{
 const start='<section id="product-evidence" class="section guidance-panel evidence-panel" aria-labelledby="evidence-title"><div class="section-heading"><h2 id="evidence-title">Product evidence</h2><span class="badge">Read-only</span></div>';
 if(!report)return start+`<h3>Evidence unavailable</h3><p>${escape(error??'No report is available in this snapshot.')}</p>${commandButton('harness product report',project)}</section>`;
 const actions=verificationActions(report),passed=report.checks.filter(c=>c.status==='passed').length,risk=report.checks.filter(c=>c.status==='accepted-risk').length;
 let html=start+`<div class="evidence-heading"><div><h3>${report.ready?'Evidence complete for the approved scope':'Evidence still needed'}</h3><p>Tasks marked done do not establish product readiness. This report reuses retained evidence; viewing it starts no model, container or VM.</p></div><div class="evidence-count"><strong>${passed} / ${report.checks.length}</strong><span>checks passed${risk?` · ${risk} accepted risk`:''}</span></div></div>`;
 if(actions.length)html+=`<div class="evidence-next"><strong>Next: ${escape(actions[0]!.title)}</strong>${commandButton('harness product verify',project)}<p class="meta">The terminal guide shows missing work and previews execution limits before you continue.</p></div>`;
 html+=`<details data-state-key="product-identity"><summary>Version, scope and evidence identity</summary><dl>${identity('Project',report.project)}${identity('Product kind',report.kind)}${identity('Source',report.source)}${identity('Approved scope',report.spec)}${identity('Selected runtime evidence',report.evidenceDigest)}</dl></details><div class="evidence-checks">`;
 for(const [i,c] of report.checks.entries()){
  const e=c.evidence,action=verificationActions({...report,checks:[c]})[0];
  html+=`<details class="evidence-check" data-state-key="evidence-${escape(c.id)}-${i}"><summary><span>${escape(checkTitle(c))}</span>${badge(c.status)}</summary><p>${escape(c.detail)}</p>`;
  if(c.status==='accepted-risk')html+='<p>Risk was explicitly accepted for this scope. This is not passed testing.</p>';
  if(e){html+=`<dl>${identity('Provider / target',e.provider+' / '+e.approval)}${identity('Subject',e.subject.kind+(e.subject.digest?' / '+e.subject.digest:''))}${identity('Runtime identity',e.runtime)}${identity('Producer / run',e.producer)}${identity('Recorded at',e.at)}${identity('Applicability / outcome',e.applicability+' / '+e.outcome)}</dl>`;
   if(e.metrics?.length)html+=`<div class="evidence-table"><table><caption>Observed model metrics</caption><thead><tr><th scope="col">Metric</th><th scope="col">Observed</th><th scope="col">Approved threshold</th><th scope="col">Baseline</th><th scope="col">Samples</th></tr></thead><tbody>${e.metrics.map(m=>`<tr><th scope="row">${escape(m.name)}</th><td>${number(m.value)} ${escape(m.unit)}</td><td>${m.comparison==='at-most'?'≤':'≥'} ${number(m.threshold)} ${escape(m.unit)}</td><td>${m.baseline===undefined?'Not specified':number(m.baseline)}</td><td>${m.samples}</td></tr>`).join('')}</tbody></table></div>`;
   if(e.lineage)html+=`<details data-state-key="lineage-${escape(e.id)}"><summary>Model and data lineage · identities only</summary><dl>${Object.entries(e.lineage).map(([k,v])=>identity(k,v)).join('')}</dl></details>`;
   if(e.artifacts.length)html+=`<h4>Retained evidence</h4><ul class="evidence-artifacts">${e.artifacts.map(a=>output(a.id,a.name,live,project)).join('')}</ul>`;
   html+=`<h4>What this does not establish</h4>${textList(e.limitations)}`;
  }
  if(c.id==='security'&&report.security){const s=report.security;html+=`<h4>Security scope</h4><dl>${identity('Scope',s.scope)}${identity('Run',s.run)}${identity('Evidence',s.evidenceDigest)}</dl>${textList(s.requirements.map(r=>`${labels[r.status]??r.status} · ${r.id}: ${r.detail}`))}`;
   for(const f of s.findings)html+=`<article class="evidence-finding"><h4>${escape(f.severity)} · ${escape(f.rule)} · ${escape(f.disposition)}</h4><p>${escape(f.summary)}</p><p>Remediation: ${escape(f.remediation)}</p>${f.rationale?`<p>Risk rationale: ${escape(f.rationale)}</p>`:''}<dl>${identity('Affected subject',f.subject)}${identity('Evidence run',f.evidence.run)}</dl><ul>${output(f.evidence.artifact,'Security observations',live,project)}</ul></article>`;
   html+=`<h4>Security limitations</h4>${textList(s.limitations)}`;
  }
  if(c.id==='performance'&&report.performance){const p=report.performance;html+=`<dl>${identity('Scope',p.scope)}${identity('Run',p.run)}${identity('Separate assessment',p.assessment)}</dl>`;
   if(p.metrics&&p.profile){const m=p.metrics,q=p.profile;html+=`<div class="evidence-table"><table><caption>Local API measurements · ${m.samples} samples</caption><thead><tr><th scope="col">Metric</th><th scope="col">Observed</th><th scope="col">Approved threshold</th></tr></thead><tbody><tr><th scope="row">Mean latency</th><td>${number(m.meanMs)} ms</td><td>≤ ${number(q.meanMs)} ms</td></tr><tr><th scope="row">Successful throughput</th><td>${number(m.throughputRps)} requests/s</td><td>≥ ${number(q.minRps)} requests/s</td></tr><tr><th scope="row">Errors</th><td>${m.errors} (${number(m.errorPercent)}%)</td><td>≤ ${number(q.maxErrorPercent)}%</td></tr><tr><th scope="row">Repetition mean spread</th><td>${number(m.spreadPercent)}%</td><td>≤ ${number(q.maxSpreadPercent)}%</td></tr></tbody></table></div>`;}
   if(p.environment)html+=`<p>Measured environment: ${escape(p.environment.os)} ${escape(p.environment.arch)} · Docker ${escape(p.environment.dockerVersion)} · ${p.environment.cpus} VM CPUs / ${number(p.environment.memoryBytes/1024**3)} GiB. App: 2 CPUs; observer: 1 CPU; 512 MiB each.</p><p class="evidence-id">Image ${escape(p.environment.image)}</p>`;
   if(p.baseline)html+=`<p>Frozen baseline ${escape(p.baseline.run)}: ${number(p.baseline.meanMs)} ms; ${number(p.baseline.throughputRps)} requests/s.</p>`;
   if(p.artifact)html+=`<ul>${output(p.artifact,'Raw timing samples',live,project)}</ul>`;
   html+=`<h4>Measurement limitations</h4>${textList(p.limitations)}`;
  }
  if(action)html+=commandButton(action.command,project);html+='</details>';
 }
 return html+'</div><p class="meta">Product scope, security, performance, human UX review and release approval are separate. Missing or unavailable evidence is never a pass.</p></section>';
}
export const PRODUCT_STYLE=`
.evidence-heading{display:flex;gap:1.5rem;justify-content:space-between;align-items:start}.evidence-heading h3{font:600 1.2rem/1.4 system-ui;color:var(--fg);text-transform:none;letter-spacing:0;margin:.4rem 0}.evidence-heading p{max-width:65ch;font-size:.9rem;color:var(--dim)}.evidence-count{display:grid;flex-shrink:0;gap:.35rem;text-align:right}.evidence-count strong{font-size:1.6rem}.evidence-count span{font-size:.75rem;color:var(--dim)}.evidence-next{padding:.8rem 1rem;background:var(--bg);border-radius:8px;margin:1rem 0}.evidence-checks{display:grid;gap:.6rem;margin:1rem 0}.evidence-check{border:1px solid var(--line);border-radius:8px;padding:.8rem;min-width:0}.evidence-check>summary{font:600 .9rem/1.5 system-ui;display:flex;justify-content:space-between;gap:.7rem;flex-wrap:wrap}.evidence-status{font-size:.75rem;border:1px solid var(--line);border-radius:20px;padding:.15rem .6rem;white-space:nowrap}.evidence-passed{color:var(--accent)}.evidence-failed{color:var(--del)}.evidence-stale,.evidence-accepted-risk{color:var(--rev)}.evidence-panel dl{display:grid;grid-template-columns:minmax(110px,1fr) minmax(0,3fr);gap:.3rem .8rem;font-size:.8rem}.evidence-panel dt{font-weight:600}.evidence-panel dd{margin:0}.evidence-id{display:block;font: .75rem/1.5 ui-monospace,monospace;overflow-wrap:anywhere}.evidence-panel p,.evidence-panel li{overflow-wrap:anywhere}.evidence-table{overflow:auto;max-width:100%;margin:1rem 0}.evidence-table table{width:100%;border-collapse:collapse;font-size:.85rem}.evidence-table caption{text-align:left;font-weight:600;margin-bottom:.5rem}.evidence-table th,.evidence-table td{padding:.6rem;border-bottom:1px solid var(--line);text-align:left}.evidence-panel h4{margin:1rem 0 .5rem}.evidence-artifacts{padding-left:1.2rem}.evidence-finding{border-left:3px solid var(--rev);padding-left:1rem}@media(max-width:600px){.evidence-heading{display:block}.evidence-count{text-align:left;margin:.7rem 0}.evidence-panel dl{grid-template-columns:1fr}.evidence-panel dd{margin-bottom:.5rem}.evidence-check{padding:.7rem}}
`;
