import {readFileSync} from 'node:fs';import {writeFile} from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';
import type {CheckManifest,CheckStep} from './checks.ts';import {OperatorError} from '../verbs/io.ts';
export const HTTP_MODULE='/harness-checks/http.mjs';
const source=readFileSync(new URL('./runtime/http.mjs',import.meta.url));
export const HTTP_DIGEST=createHash('sha256').update(source).digest('hex');
export function assertHttpRuntimes(manifest:CheckManifest):void{for(const c of manifest.cases)for(const s of c.steps){const imports=s.command.some(a=>a.includes(HTTP_MODULE));if((s.httpRuntime!==undefined&&s.httpRuntime!==HTTP_DIGEST)||(imports&&s.httpRuntime!==HTTP_DIGEST))throw new OperatorError(`${c.id}: HTTP helper is missing or changed since this check was prepared.`,'Run harness checks prepare, then review and approve the refreshed checks.');}}
export function pinHttpRuntime(step:CheckStep):void{if(step.command.some(a=>a.includes(HTTP_MODULE)))step.httpRuntime=HTTP_DIGEST;else delete step.httpRuntime;}
export async function writeHttpRuntime(directory:string):Promise<void>{await writeFile(path.join(directory,'http.mjs'),source,{mode:0o444,flag:'wx'});}
export function httpRuntimePrompt():string{return `For new Node HTTP probes import {observeHttp,observeJson} from '${HTTP_MODULE}' and set httpRuntime:'${HTTP_DIGEST}' on importing steps. These tested helpers are host-owned and mounted read-only. Do not copy HTTP transport code into new probes.
await observeHttp(url,{method,headers,body,timeoutMs:5000,maxBytes:1048576}) returns {url,status,headers,text}. Redirects are always manual, headers are retained with lowercase names, body reads have time/byte limits. await observeJson(url,{method,json,...options}) additionally validates a JSON media type and returns parsed data; it supplies Origin and application/json for POST/PUT/PATCH/DELETE, including bodyless requests. Use observeHttp with explicit headers/body for negative tests of missing Origin, wrong content type, malformed JSON, etc. Do not let positive-request defaults mask a negative test.
Assert the exact contracted status and response shapes yourself. Scan BOTH headers and raw/parsed body for applicable private markers; do not scan only data. JSON escaping may change raw spelling: inspect decoded fields as well. Helpers do not assert application behaviour or prove privacy. Preserve existing reviewed code unless that check needs a repair.`;}
export function httpRuntimeReview(steps:readonly CheckStep[]):string{return steps.some(s=>s.httpRuntime!==undefined||s.command.some(a=>a.includes(HTTP_MODULE)))?httpRuntimePrompt()+'\nExact HTTP helper source, SHA-256 '+HTTP_DIGEST+':\n'+source.toString('utf8'):'';}
