import {createHash} from 'node:crypto';import path from 'node:path';import {mkdir,readFile} from 'node:fs/promises';import type {Feature} from '../features.ts';import {readApproval,acceptanceTaskScope} from './checks.ts';import {readProfile} from '../project/profile.ts';import {getAdapter} from '../adapters/registry.ts';import {sourceFiles} from '../workspace/candidate.ts';import {safePath} from '../workspace/safe-path.ts';import {readArtifact,atomicWrite} from '../planning/store.ts';import {harnessDirectory} from '../record/record.ts';import {requestCheckJson,taskDigest} from './draft.ts';import {planInStages,type PlanningContext,type OutlinePlanning} from './planning-stages.ts';import type {Proposal} from './draft.ts';import {OperatorError} from '../verbs/io.ts';
export async function planningContext(project:string,task:Feature):Promise<PlanningContext>{
 const approval=await readApproval(project),tasks=approval?(await acceptanceTaskScope(project,[task.id],approval)).filter(id=>id!==task.id):[];
 const cases=approval?.manifest.cases.filter(c=>c.tasks.includes('*')||c.tasks.some(t=>tasks.includes(t)))??[];
 const profile=await readProfile(project,true),adapter=getAdapter(profile.adapter),files=await sourceFiles(project,'',adapter.source.generatedDirectories);const facts=[];
 for(const file of Object.keys(files).sort().filter(f=>f==='package.json'||f==='pyproject.toml'||/^(?:(?:src|public)\/)?(?:app|main|server|index)\.(?:js|mjs|cjs|ts|py)$/u.test(f)||(!/^tests?\//u.test(f)&&/(?:^|\/)contracts?(?:\/|[.-])/iu.test(f)))){const bytes=await readFile(await safePath(project,file));if(bytes.includes(0)||bytes.length>32*1024)throw new OperatorError('Shared source context exceeds its bounded text limit: '+file);facts.push({file,text:bytes.toString()});}
 const context={approvedContracts:[...new Set(cases.map(c=>c.contract).filter((v):v is string=>!!v))],sourceFacts:JSON.stringify({files:Object.keys(files).sort(),selectedSources:facts,limitation:'Only listed source contents were inspected; filenames alone establish no behavior.'}),prerequisites:JSON.stringify({approval:approval?.digest,tasks,checks:cases.map(c=>({id:c.id,tasks:c.tasks,description:c.description}))}),runtime:JSON.stringify({adapter:profile.adapter,runner:profile.runner,requirements:profile.requirements,commandChecks:'Offline disposable container; no browser/GUI. Browser and source evidence are separate and limitations never waive criteria.'})};
 if(Buffer.byteLength(JSON.stringify(context))>64*1024)throw new OperatorError('Approved interface/source context exceeds the 64 KiB planning limit.','Split or explicitly revise duplicated context; no contract or requirement was truncated.');return context;
}
export async function prepareOutline(project:string,task:Feature,source:string,feedback:string,previous:Proposal|undefined,issues:readonly string[],progress:(s:string)=>void){
 const context=await planningContext(project,task),prior=previous?{contract:previous.contract,coverage:previous.coverage,behaviours:previous.manifest.cases.map(c=>({id:c.id,description:c.description}))}:undefined;
 const identity=createHash('sha256').update(JSON.stringify({policy:2,task:taskDigest(task),source,context,feedback,prior,issues})).digest('hex'),directory=path.join(harnessDirectory(project),'acceptance');
 const file='outline-planning.json',raw=await readArtifact(directory,file,8*1024*1024),old=raw?JSON.parse(raw) as OutlinePlanning:undefined;await mkdir(directory,{recursive:true,mode:0o700});
 const save=(state:OutlinePlanning)=>atomicWrite(path.join(directory,file),JSON.stringify(state,null,2)+'\n');
 progress(`Planning packet: ${Buffer.byteLength(JSON.stringify(context))} bytes; ${context.approvedContracts.length} inherited approved contract(s); ${task.criteria.length} criterion stages. No exploration tools.`);
 return planInStages(task,context,identity,{request:(stage,prompt)=>requestCheckJson(project,prompt,{tools:'none',stage:'planning-'+stage}),save,progress},old?.identity===identity?old:undefined,feedback,{prior,issues});
}
