import {terminalDialogue,choose,confirmed,type Dialogue} from '../guide/dialogue.ts';import {withWriter} from '../workspace/writer-lock.ts';import {assertProductCurrent} from '../product/spec.ts';import {productReport} from '../product/report.ts';import {approveSecurity,readSecurity} from '../security/store.ts';import {verifySecurity,recoverSecurity} from '../security/controller.ts';import {recordSecurityAssessment,acceptSecurityRisk} from '../security/report.ts';import {parseScope,type Scope} from '../security/schema.ts';import {say,OperatorError} from './io.ts';
export async function securitySetup(project:string,io:Dialogue=terminalDialogue()){
 const product=await assertProductCurrent(project);if(!product)throw new OperatorError('Approve product requirements first: harness product setup.');const previous=await readSecurity(project),old=previous?.scope;
 io.write('Security scope uses accepted product requirements. Enter synthetic values only; never paste real passwords, API keys or private stories.');for(const t of product.requirements.tasks as {id:string;title:string}[])io.write(`${t.id}: ${t.title}`);
 const ask=async(label:string,def:string)=>(await io.ask(`${label} (Enter for ${def}):`)).trim()||def;
 const assets=await ask('What information needs protection?',old?.assets??'Private content and management keys'),interfaces=await ask('Which interfaces expose it?',old?.interfaces??'Local HTTP API'),boundaries=await ask('Which callers must be kept separate?',old?.boundaries??'Public readers and private content owners');
 const taskText=await ask('Accepted task IDs whose application checks cover security, comma-separated; none to skip',old?.acceptanceTasks.join(',')||'none'),acceptanceTasks=taskText==='none'?[]:taskText.split(',').map(x=>x.trim());
 const lane=await choose(io,'Automated security coverage',['Local Node API with bearer management keys and a synthetic creation endpoint','Unsupported or manual-only target; keep automated evidence unavailable']);if(lane<0)return;
 const dependency=await choose(io,'Third-party dependency vulnerability intelligence',['Not configured; keep this evidence unavailable','No third-party package inputs; record a scoped not-applicable rationale']);if(dependency<0)return;
 const explanation=await ask('Explain the dependency-intelligence scope',old?.dependencyReview.rationale??(dependency===0?'No pinned vulnerability scanner or current feed is configured.':'This project declares no third-party package inputs; runtime vulnerabilities need separate review.'));
 const scope:Scope={version:1,assets,interfaces,boundaries,acceptanceTasks,dependencyReview:{mode:dependency===0?'unavailable':'not-applicable',rationale:explanation}};
 if(lane===0){
  const r=old?.recipe;const entry=await ask('Server entry file',r?.entry??'src/server.js'),databaseEnv=await ask('Database environment variable, or none',r?.databaseEnv??'none');
  const publicPath=await ask('Public reading path',r?.publicPath??'/api/stories'),createPath=await ask('Path that creates synthetic pending content',r?.createPath??'/api/stories'),privatePath=await ask('Owner-only reading path',r?.privatePath??'/api/author/story'),keyField=await ask('Top-level response field containing the new management key',r?.keyField??'managementKey');
  let fields=r?.fields??{title:'Harness synthetic check',body:'$MARKER',contentNote:null};
  const edit=await choose(io,'Synthetic creation fields',['Use '+JSON.stringify(fields),'Enter field names and synthetic values']);if(edit<0)return;
  if(edit===1){fields={};io.write('Use $MARKER in at least one text value; it becomes a fresh synthetic identifier. Enter an empty field name to finish.');for(let i=0;i<12;i++){const name=(await io.ask('Field name:')).trim();if(!name)break;const value=await io.ask('Synthetic value (null for JSON null):');fields[name]=value==='null'?null:value;}}
  const pending=await confirmed(io,'Should newly created content remain absent from public responses until moderation?');
  const timeoutSeconds=Number(await ask('Maximum seconds per verification (15–180)',String(r?.timeoutSeconds??60)));
  scope.recipe={entry,port:r?.port??3847,timeoutSeconds,...(databaseEnv==='none'?{}:{databaseEnv}),createPath,privatePath,publicPath,keyField,fields,createStatus:201,deniedStatus:401,originStatus:403,hostStatus:403,pendingPrivate:pending};
  io.write('Expected: creation 201; valid owner/public reads 200; missing/invalid keys 401; foreign Host/Origin 403; text/plain creation 415.');
  if(await confirmed(io,'Do any of those status codes need changing?')){scope.recipe.createStatus=Number(await ask('Creation status (200 or 201)','201')) as 201;scope.recipe.deniedStatus=Number(await ask('Missing/invalid key status (401 or 403)','401')) as 401;scope.recipe.originStatus=Number(await ask('Foreign Origin status (400 or 403)','403')) as 403;scope.recipe.hostStatus=Number(await ask('Foreign Host status (400 or 403)','403')) as 403;}
 }
 const image=previous?.image??process.env.HARNESS_IMAGE_ID??'';if(!/^sha256:[a-f0-9]{64}$/u.test(image))throw new OperatorError('Configure an immutable HARNESS_IMAGE_ID before approving this scope.');
 parseScope(scope);io.write(JSON.stringify(scope,null,2));io.write(`Runtime: ${image}. Offline app and separate probe containers; 2 CPUs and 512 MiB each; synthetic disposable data only. No scans run during setup. No provider calls or dependency downloads.`);io.write('High-severity findings and sensitive-product findings cannot be risk-accepted. Coverage limits need a separate security assessment.');
 if(await confirmed(io,'Approve this security scope and verification budget?')){await withWriter(project,'security setup',()=>approveSecurity(project,scope,image,product.digest));io.write('Security scope saved. Next: harness security verify');}
}
export async function securityCommand(project:string,args:readonly string[]){const [action,id,...extra]=args;if(extra.length)throw new OperatorError('Too many security arguments.');
 if(action==='setup'&&!id)return securitySetup(project);
 if(action==='verify'&&!id){const r=await verifySecurity(project,say);say('Retained run: '+r.id);if(r.status!=='passed')process.exitCode=1;return;}
 if(action==='recover'&&id)return recoverSecurity(project,id);
 if((action==='report'||!action)&&(!id||id==='--json')){const product=await productReport(project);if(!product.security)throw new OperatorError('Approve product requirements first.');const report=product.security;if(id==='--json')say(JSON.stringify(report,null,2));else{say('Scoped security: '+report.status);for(const r of report.requirements)say(`${r.status}: ${r.id} — ${r.detail}`);for(const f of report.findings)say(`${f.severity}: ${f.rule} — ${f.summary} [${f.disposition}]\n  ${f.remediation}`);say('Next: '+report.next);report.limitations.forEach(say);}if(!report.complete)process.exitCode=1;return;}
 if((action==='assess'&&!id)||(action==='accept-risk'&&id)){
  const io=terminalDialogue(),product=await productReport(project),report=product.security;if(!report?.scope||!report.evidenceDigest)throw new OperatorError('Review a current security report first.');
  io.write(JSON.stringify(report,null,2));const notes=await io.ask('Explain the evidence, scope and limitations (20–1500 characters; no secrets):');const passed=action==='assess'?await confirmed(io,'Does your separate security assessment pass?'):false;
  if(await confirmed(io,action==='assess'?'Save this security assessment?':'Accept this scoped risk under the displayed policy?'))await withWriter(project,'security assessment',async()=>{const fresh=await productReport(project);if(fresh.security?.evidenceDigest!==report.evidenceDigest)throw new OperatorError('Security evidence changed; review it again.');if(action==='assess')await recordSecurityAssessment(project,report,passed,notes);else{const spec=await assertProductCurrent(project);await acceptSecurityRisk(project,report,spec!.consequence,id!,notes);}});return;
 }
 throw new OperatorError('Use harness security setup | verify | report [--json] | assess | accept-risk <finding-rule> | recover <run-id>.');
}
