import {countLeaks} from './instrumentation/scan.mjs';
import {randomUUID} from 'node:crypto';import {mkdir,writeFile,readFile,rm} from 'node:fs/promises';import path from 'node:path';
import {run} from '../run.ts';import {withWriter} from '../workspace/writer-lock.ts';import {captureBaseline,assertLiveBaseline,assertSnapshot} from '../workspace/candidate.ts';import {assertProductCurrent} from '../product/spec.ts';import {sha256,putArtifact} from '../artifacts/store.ts';import {boundedOutput} from '../desktop/output.ts';import {EvidenceReader} from '../product/evidence/reader.ts';import {uuidId} from '../product/evidence/schema.ts';
import {assess,parseObservations,type Recipe} from './schema.ts';import {resources,readSecurity,securityProtocol,parseRun,saveRun,securityRoot,type SecurityRun} from './store.ts';
export function common(r:SecurityRun,name:string){return ['run','--init','--name',name,'--label',`harness.security=${r.id}`,'--label',`harness.token=${r.token}`,'--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--cpus=2','--memory=512m','--pids-limit=128','--user',`${process.getuid?.()??501}:${process.getgid?.()??20}`,'--tmpfs','/tmp:rw,nosuid,nodev,size=64m','--env','HOME=/tmp','--log-driver','local','--log-opt','max-size=1m','--log-opt','max-file=2','--entrypoint','timeout'];}
export function appArguments(r:SecurityRun,name:string,source:string,s:Recipe){return [...common(r,name),'--detach','--network=none','--tmpfs','/work:rw,nosuid,nodev,mode=1777,size=128m','--mount',`type=bind,src=${source},dst=/app,readonly`,'--workdir','/app','--env',`PORT=${s.port}`,...(s.databaseEnv?['--env',`${s.databaseEnv}=/work/security.sqlite`]:[]),r.image,'-k','3',String(s.timeoutSeconds+30),'node',s.entry];}
export function probeArguments(r:SecurityRun,name:string,app:string,root:string,s:Recipe){return [...common(r,name),'--network',`container:${app}`,'--mount',`type=bind,src=${resources}/instrumentation,dst=/harness-instrumentation,readonly`,'--mount',`type=bind,src=${root}/checks,dst=/harness-checks,readonly`,'--mount',`type=bind,src=${root}/output,dst=/work`,'--workdir','/work',r.image,'-k','3',String(s.timeoutSeconds),'node','/harness-instrumentation/probe.mjs'];}
async function owned(r:SecurityRun,name:string){const v=await run(r.docker,['inspect',name],{timeoutMs:10000,maxOutputBytes:1024*1024});if(v.code!==0){if(!v.timedOut&&!v.outputLimited&&/no such (object|container)/iu.test(v.stderr))return false;throw Error('Cannot inspect owned security containers.');}if(v.timedOut||v.outputLimited)throw Error('Container inspection incomplete.');const m=JSON.parse(v.stdout)[0];if(m?.Image!==r.image||m?.Config?.Labels?.['harness.security']!==r.id||m?.Config?.Labels?.['harness.token']!==r.token)throw Error('Security container ownership mismatch.');return true;}
async function cleanup(r:SecurityRun){for(const n of [...r.containers].reverse())if(await owned(r,n)){const result=await run(r.docker,['rm','-f',n],{timeoutMs:15000,maxOutputBytes:10000});if(result.code!==0||result.timedOut)throw Error('Security cleanup needs recovery.');if(await owned(r,n))throw Error('Security container still exists.');}r.containers=[];}
async function files(root:string){for(const part of ['source','checks','output'])await rm(path.join(root,part),{recursive:true,force:true});}
export async function recoverSecurity(project:string,id:string){if(!uuidId(id,'security-run'))throw Error('Invalid security run ID.');return withWriter(project,'security recover',async()=>{const reader=new EvidenceReader(project+'-harness'),r=parseRun(await reader.json(`security/runs/${id}/state.json`));if(r.id!==id)throw Error('Security run identity changed.');if(!['running','preparing'].includes(r.status))return;await cleanup(r);await files((await securityRoot(project))+'/runs/'+id);r.status='interrupted';r.message='Owned security resources removed; verify the approved scope again.';await saveRun(project,r);});}
export async function verifySecurity(project:string,notify:(s:string)=>void=()=>{},docker=process.env.HARNESS_DOCKER?.trim()||'/usr/local/bin/docker'){
 return withWriter(project,'security verify',async()=>{
 const a=await readSecurity(project),product=await assertProductCurrent(project);if(!a||!a.scope.recipe)throw Error('Approve a supported local security recipe first: harness security setup.');if(a.product!==product?.digest||a.protocol!==await securityProtocol())throw Error('Security scope or rules changed. Review security setup.');
 const reader=new EvidenceReader(project+'-harness');for(const id of await reader.names('security/runs')){if(id.startsWith('.'))continue;const r=parseRun(await reader.json(`security/runs/${id}/state.json`));if(['preparing','running'].includes(r.status))throw Error('Recover the unfinished security run first: harness security recover '+r.id);}
 const r:SecurityRun={version:1,id:'security-run-'+randomUUID(),at:new Date().toISOString(),approval:a.digest,product:a.product,protocol:a.protocol,image:a.image,docker,token:randomUUID(),status:'preparing',containers:[],message:'Preparing isolated security checks.'};await saveRun(project,r);const root=(await securityRoot(project))+'/runs/'+r.id,s=a.scope.recipe,abort=new AbortController(),cancel=()=>abort.abort();process.on('SIGINT',cancel);process.on('SIGTERM',cancel);let stage='source preparation';
 try{
  if(root.includes(','))throw Error('Mount path unsupported.');
  const snapshot=await captureBaseline(project,root+'/source');if(!Object.hasOwn(snapshot.files,s.entry))throw Error('Server entry missing.');
  const pkg=JSON.parse(await readFile(snapshot.directory+'/package.json','utf8'));if(pkg.workspaces||['dependencies','optionalDependencies'].some(k=>Object.keys(pkg[k]??{}).length))throw Error('Security recipe requires a dependency-free Node server.');
  let total=0;for(const f of Object.keys(snapshot.files)){total+=(await boundedOutput(snapshot.directory,f,4*1024*1024)).length;if(total>32*1024*1024)throw Error('Source limit exceeded.');}
  r.source=snapshot.digest;r.identity=sha256(JSON.stringify({source:r.source,approval:a.digest,image:r.image,protocol:r.protocol}));await mkdir(root+'/checks');await mkdir(root+'/output');
  const {createStatus:_,deniedStatus:_d,hostStatus:_h,originStatus:_o,...actions}=s;await writeFile(root+'/checks/request.json',JSON.stringify(actions),{mode:0o600});
  const app='harness-security-'+randomUUID(),probe='harness-security-'+randomUUID();r.containers=[app,probe];r.status='running';r.message='Running approved probes against an offline disposable app.';await saveRun(project,r);notify(r.message);
  stage='application startup';const start=await run(docker,appArguments(r,app,snapshot.directory,s),{timeoutMs:15000,maxOutputBytes:10000,signal:abort.signal});if(start.code!==0||start.timedOut||start.outputLimited)throw Error('App failed to start.');
  const timer=setInterval(()=>notify('Security probes running; '+s.timeoutSeconds+' second limit.'),10000);
  stage='probe execution';const result=await run(docker,probeArguments(r,probe,app,root,s),{timeoutMs:(s.timeoutSeconds+5)*1000,maxOutputBytes:10000,signal:abort.signal}).finally(()=>clearInterval(timer));if(result.code!==0||result.timedOut||result.outputLimited)throw Error('Probe did not complete.');
  stage='application shutdown';if(!await owned(r,app))throw Error('App disappeared before log inspection.');const stop=await run(docker,['stop','--time','3',app],{timeoutMs:10000,maxOutputBytes:10000});if(stop.code!==0||stop.timedOut)throw Error('App shutdown incomplete.');
  stage='log inspection';const logs=await run(docker,['logs',app],{timeoutMs:10000,maxOutputBytes:512*1024});if(logs.code!==0||logs.timedOut||logs.outputLimited)throw Error('Complete log evidence unavailable.');
  stage='observation collection';const secrets=JSON.parse((await boundedOutput(root+'/output','synthetic-secrets.json',20000)).toString());for(const name of ['keys','markers'])if(!Array.isArray(secrets[name])||secrets[name].length!==2||secrets[name].some((v:unknown)=>typeof v!=='string'||v.length<16||v.length>4096))throw Error('Synthetic observation incomplete.');
  const observed=JSON.parse((await boundedOutput(root+'/output','observations.json',10000)).toString());
  const count=(values:string[])=>countLeaks(logs.stdout+'\n'+logs.stderr,values);
  const observations=parseObservations({...observed,logKeyLeaks:count(secrets.keys),logBodyLeaks:count(secrets.markers),logsComplete:true});
  await assertSnapshot(snapshot);await assertLiveBaseline(project,snapshot);if((await readSecurity(project))?.digest!==a.digest||await securityProtocol()!==a.protocol)throw Error('Security authority changed.');
  const artifact=await putArtifact(project,'security-observations.json',Buffer.from(JSON.stringify(observations)),{producer:r.id,input:r.source,environment:r.identity,verification:'unverified'});r.report=artifact.id;const findings=assess(a.scope,observations);r.status=findings.length?'failed':'passed';r.message=findings.length?`${findings.length} scoped security finding(s).`:'Selected security probes matched; this is not a comprehensive security assessment.';
 }catch{r.status=abort.signal.aborted?'interrupted':'failed';r.message=abort.signal.aborted?'Security verification interrupted; no complete result.':`Security verification incomplete at ${stage}. Check the approved entry, paths and runtime; raw app output is withheld to protect secrets.`;}
 finally{process.off('SIGINT',cancel);process.off('SIGTERM',cancel);try{await cleanup(r);}catch{r.status='running';r.message='Security cleanup needs recovery.';await saveRun(project,r);throw Error('Run harness security recover '+r.id);}await files(root);await saveRun(project,r);notify(r.status+': '+r.message);}
 return r;
 });
}
