import {assertProductCurrent} from '../product/spec.ts';
import {sha256,saveJson} from '../artifacts/store.ts';import {EvidenceReader} from '../product/evidence/reader.ts';import {hash,uuidId,object,timestamp} from '../product/evidence/schema.ts';import {parseApproval,parseRun,securityProtocol,securityRoot,type Approval,type SecurityRun} from './store.ts';import {assess,rationale,type RuleFinding} from './schema.ts';
export interface Context {source:string;product:string;consequence:'prototype'|'sensitive';acceptance:{id:string;status:string;detail?:string}[];}
export interface Finding extends RuleFinding {subject:string;scope:string;evidence:{run:string;artifact:string};disposition:'open'|'accepted-risk';rationale?:string;}
export interface SecurityReport {version:1;status:'passed'|'failed'|'missing'|'stale'|'unavailable'|'accepted-risk';complete:boolean;configured?:boolean;source:string;scope?:string;evidenceDigest?:string;run?:string;findings:Finding[];requirements:{id:string;status:string;detail:string}[];limitations:string[];next:string;}
const limitations=['Fixed synthetic local API probes cover only the approved endpoints and scenarios.','No penetration-test certification, dependency vulnerability intelligence, production assurance or performance assessment.','Artifact identities detect accidental substitution; host records are not attestations against a malicious operator.'];
export async function securityReport(project:string,context:Context):Promise<SecurityReport>{
 const reader=new EvidenceReader(project+'-harness'),sourceReader=new EvidenceReader(project),out:SecurityReport={version:1,status:'missing',complete:false,source:context.source,findings:[],requirements:[],limitations,next:'harness security setup'};
 try{
  const raw=await reader.json('security/approved.json');if(!raw)return out;out.configured=true;const a=parseApproval(raw);out.scope=a.digest;
  if(a.product!==context.product||a.consequence!==context.consequence||a.protocol!==await securityProtocol()){out.status='stale';return out;}
  const selected:SecurityRun[]=[];for(const id of await reader.names('security/runs')){if(id.startsWith('.'))continue;if(!uuidId(id,'security-run'))throw Error('Invalid security run directory.');const run=parseRun(await reader.json(`security/runs/${id}/state.json`));if(run.id!==id)throw Error('Run identity changed.');if(run.approval===a.digest)selected.push(run);}
  const matching=selected.filter(r=>r.source===context.source||!r.source).sort((a,b)=>a.at.localeCompare(b.at)||a.id.localeCompare(b.id)),last=matching.at(-1);
  if(last&&matching.filter(r=>r.at===last.at).length!==1)throw Error('Ambiguous security run order.');
  out.next='harness security verify';let findings:RuleFinding[]=[];
  if(!a.scope.recipe)out.requirements.push({id:'probes',status:'unavailable',detail:'No supported local Node API recipe selected. Desktop and ML security remain separate evidence obligations.'});
  else if(!last)out.requirements.push({id:'probes',status:selected.length?'stale':'missing',detail:'No current-source run for this security scope.'});
  else{
   out.run=last.id;
   if(last.containers.length||['preparing','running'].includes(last.status)){out.requirements.push({id:'probes',status:'failed',detail:'Security execution or owned resource cleanup is unfinished.'});out.next='harness security recover '+last.id;}
   else if(!last.source||!last.report||!['passed','failed'].includes(last.status))out.requirements.push({id:'probes',status:'failed',detail:'Security verification did not retain complete observations.'});
   else{
    const identity=sha256(JSON.stringify({source:context.source,approval:a.digest,image:a.image,protocol:a.protocol}));if(last.identity!==identity||last.product!==a.product||last.protocol!==a.protocol||last.image!==a.image)throw Error('Security execution identity changed.');
    const result=await reader.artifact(last.report),artifact=result.artifact;if(artifact.name!=='security-observations.json'||artifact.producer!==last.id||artifact.input!==context.source||artifact.environment!==identity)throw Error('Security observations substituted.');findings=assess(a.scope,JSON.parse(result.bytes.toString()));
    out.findings=findings.map(f=>({...f,subject:context.source,scope:a.digest,evidence:{run:last.id,artifact:last.report!},disposition:'open'}));
    out.requirements.push({id:'probes',status:findings.length?'failed':'passed',detail:findings.length?`${findings.length} observed scoped finding(s).`:'Host comparisons matched the approved local API scope.'});
   }
  }
  for(const task of a.scope.acceptanceTasks){const present=context.acceptance.find(c=>c.id==='acceptance:'+task);out.requirements.push({id:'acceptance:'+task,status:present?.status==='passed'?'passed':'missing',detail:present?.status==='passed'?'Existing current approved application evidence reused.':'Needs current approved acceptance evidence for the selected task.'});}
  if(a.scope.dependencyReview.mode==='unavailable')out.requirements.push({id:'dependency-intelligence',status:'unavailable',detail:'No pinned scanner, rule set or fresh vulnerability feed. Offline absence is not a clean scan.'});
  else{const pkg=await sourceReader.json('package.json') as any,lock=await sourceReader.json('package-lock.json') as any;const dependencies=!pkg||['dependencies','devDependencies','optionalDependencies','peerDependencies'].some(k=>pkg[k]&&Object.keys(pkg[k]).length)||pkg.workspaces||(lock?.packages&&Object.keys(lock.packages).some(k=>k!==''))||(lock?.dependencies&&Object.keys(lock.dependencies).length);out.requirements.push({id:'dependency-intelligence',status:dependencies?'unavailable':'not-applicable',detail:dependencies?'Third-party package inputs exist or cannot be inventoried; no scanner is configured.':'Operator scoped third-party dependency intelligence as not applicable; no declared third-party package inputs found. Runtime vulnerabilities remain outside these probes.'});}
  out.evidenceDigest=sha256(JSON.stringify({source:context.source,approval:a.digest,protocol:a.protocol,read:reader.digest(),sourceRead:sourceReader.digest(),acceptance:context.acceptance.filter(c=>a.scope.acceptanceTasks.includes(c.id.replace(/^acceptance:/u,''))),requirements:out.requirements,findings:out.findings}));
  const decisions=await reader.json('security/dispositions.json');if(decisions){const d=object(decisions,['version','scope','evidence','at','decisions']);if(d.version!==1||!hash(d.scope)||!hash(d.evidence)||!timestamp(d.at)||!Array.isArray(d.decisions)||d.decisions.length>20)throw Error('Invalid security dispositions.');if(d.scope===a.digest&&d.evidence===out.evidenceDigest){const seen=new Set();for(const item of d.decisions){const value=object(item,['rule','disposition','rationale']);if(typeof value.rule!=='string'||seen.has(value.rule)||value.disposition!=='accepted-risk')throw Error('Invalid security disposition.');seen.add(value.rule);const f=out.findings.find(f=>f.rule===value.rule);if(!f||!canAccept(context.consequence,f))throw Error('Policy forbids this risk acceptance.');f.disposition='accepted-risk';f.rationale=rationale(value.rationale);}}}
  const assessment=await reader.json('security/assessment.json');let human='missing';if(assessment){const s=object(assessment,['version','scope','evidence','at','passed','notes']);if(s.version!==1||!hash(s.scope)||!hash(s.evidence)||!timestamp(s.at)||typeof s.passed!=='boolean')throw Error('Invalid security assessment.');rationale(s.notes);human=s.scope!==a.digest||s.evidence!==out.evidenceDigest?'stale':s.passed?'passed':'failed';}
  out.requirements.push({id:'security-assessment',status:human,detail:'Separate operator review of the scoped security coverage and remaining limits.'});
  const accepted=out.findings.length>0&&out.findings.every(f=>f.disposition==='accepted-risk');if(accepted){const probes=out.requirements.find(r=>r.id==='probes');if(probes?.status==='failed')probes.status='accepted-risk';}
  out.complete=out.requirements.every(r=>['passed','not-applicable','accepted-risk'].includes(r.status));out.status=out.complete?(accepted?'accepted-risk':'passed'):out.requirements.some(r=>r.status==='failed')?'failed':out.requirements.some(r=>r.status==='stale')?'stale':out.requirements.some(r=>r.status==='unavailable')?'unavailable':'missing';
  if(out.complete)out.next='harness product report';
  if(!a.scope.recipe||out.requirements.some(r=>r.id==='dependency-intelligence'&&r.status==='unavailable'))out.next='harness security setup';
  if(!out.complete&&out.requirements.filter(r=>r.id!=='security-assessment').every(r=>['passed','not-applicable','accepted-risk'].includes(r.status)))out.next='harness security assess';
  await reader.assertUnchanged();await sourceReader.assertUnchanged();return out;
 }catch{out.complete=false;out.status='failed';out.findings=[];out.requirements.push({id:'evidence-integrity',status:'failed',detail:'Security evidence is malformed, changed, incomplete or violates policy. No raw record content is displayed.'});out.next='harness security verify';return out;}
}
export function canAccept(consequence:string,f:RuleFinding){return consequence==='prototype'&&f.severity!=='high';}
export async function recordSecurityAssessment(project:string,report:SecurityReport,passed:boolean,notes:string){if(!report.scope||!report.evidenceDigest)throw Error('Review a current security report first.');await saveJson(await securityRoot(project),'assessment.json',{version:1,scope:report.scope,evidence:report.evidenceDigest,at:new Date().toISOString(),passed,notes:rationale(notes)});}
export async function acceptSecurityRisk(project:string,report:SecurityReport,consequence:string,rule:string,notes:string){const product=await assertProductCurrent(project);if(product?.consequence!==consequence)throw Error('Risk policy does not match the approved product.');const finding=report.findings.find(f=>f.rule===rule);if(!report.scope||!report.evidenceDigest||!finding||!canAccept(consequence,finding))throw Error('High-severity findings and sensitive-product findings cannot be accepted as risk.');const decisions=report.findings.filter(f=>f.disposition==='accepted-risk'&&f.rule!==rule).map(f=>({rule:f.rule,disposition:'accepted-risk',rationale:f.rationale}));decisions.push({rule,disposition:'accepted-risk',rationale:rationale(notes)});await saveJson(await securityRoot(project),'dispositions.json',{version:1,scope:report.scope,evidence:report.evidenceDigest,at:new Date().toISOString(),decisions});}
