import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import path from 'node:path';
import {saveJson,safeDirectory,stateRoot,sha256} from '../artifacts/store.ts';import {assertProductCurrent} from '../product/spec.ts';import {EvidenceReader} from '../product/evidence/reader.ts';import {object,hash,uuidId,timestamp} from '../product/evidence/schema.ts';import {parseScope,type Scope} from './schema.ts';
export const resources=import.meta.dirname;
export async function securityProtocol(){return sha256(Buffer.concat(await Promise.all(['schema.ts','store.ts','controller.ts','report.ts','instrumentation/probe.mjs','instrumentation/scan.mjs','../run.ts','../workspace/candidate.ts','../workspace/safe-path.ts','../desktop/output.ts','../artifacts/store.ts','../product/evidence/reader.ts'].map(f=>readFile(path.join(resources,f))))));}
export interface Approval {version:1;id:string;at:string;product:string;consequence:'prototype'|'sensitive';scope:Scope;image:string;protocol:string;digest:string;}
export interface SecurityRun {version:1;id:string;at:string;approval:string;product:string;protocol:string;image:string;docker:string;token:string;status:'preparing'|'running'|'passed'|'failed'|'interrupted';containers:string[];source?:string;identity?:string;report?:string;message:string;}
export async function securityRoot(project:string){const root=path.join(await stateRoot(project),'security');await safeDirectory(root);await safeDirectory(root+'/runs');return root;}
export function parseApproval(raw:unknown):Approval{const a=object(raw,['version','id','at','product','consequence','scope','image','protocol','digest']),{digest,...body}=a;if(a.version!==1||!uuidId(a.id,'security-scope')||!timestamp(a.at)||!hash(a.product)||!hash(a.protocol)||!['prototype','sensitive'].includes(String(a.consequence))||typeof a.image!=='string'||!/^sha256:[a-f0-9]{64}$/u.test(a.image)||digest!==sha256(JSON.stringify(body)))throw Error('Invalid security approval.');parseScope(a.scope);return a as unknown as Approval;}
export async function approveSecurity(project:string,scope:unknown,image:string,expectedProduct?:string){const product=await assertProductCurrent(project);if(!product)throw Error('Approve product requirements before security setup.');if(expectedProduct&&product.digest!==expectedProduct)throw Error('Product requirements changed during security setup.');const parsed=parseScope(scope),tasks=new Set((product.requirements.tasks as {id:string}[]).map(t=>t.id));if(parsed.acceptanceTasks.some(t=>!tasks.has(t)))throw Error('Select accepted task IDs for security evidence.');const body={version:1 as const,id:'security-scope-'+randomUUID(),at:new Date().toISOString(),product:product.digest,consequence:product.consequence,scope:parsed,image,protocol:await securityProtocol()},a=parseApproval({...body,digest:sha256(JSON.stringify(body))});await saveJson(await securityRoot(project),'approved.json',a);return a;}
export async function readSecurity(project:string){const reader=new EvidenceReader(project+'-harness'),raw=await reader.json('security/approved.json');if(!raw)return undefined;const a=parseApproval(raw);await reader.assertUnchanged();return a;}
export function parseRun(raw:unknown):SecurityRun{const r=object(raw,['version','id','at','approval','product','protocol','image','docker','token','status','containers','source','identity','report','message']);
 if(r.version!==1||!uuidId(r.id,'security-run')||!timestamp(r.at)||!hash(r.approval)||!hash(r.product)||!hash(r.protocol)||typeof r.image!=='string'||!/^sha256:[a-f0-9]{64}$/u.test(r.image)||typeof r.docker!=='string'||!path.isAbsolute(r.docker)||typeof r.token!=='string'||!/^[a-f0-9-]{36}$/u.test(r.token)||!['preparing','running','passed','failed','interrupted'].includes(String(r.status))||typeof r.message!=='string'||r.message.length>500||!Array.isArray(r.containers)||r.containers.length>2||r.containers.some(n=>typeof n!=='string'||!/^harness-security-[a-f0-9-]{36}$/u.test(n))||(r.source!==undefined&&!hash(r.source))||(r.identity!==undefined&&!hash(r.identity))||(r.report!==undefined&&!uuidId(r.report,'artifact')))throw Error('Invalid security run.');return r as unknown as SecurityRun;
}
export async function saveRun(project:string,r:SecurityRun){parseRun(r);const root=(await securityRoot(project))+'/runs/'+r.id;await safeDirectory(root);await saveJson(root,'state.json',r);}
